#!/usr/bin/env bash
# targets/vm/build.sh — Build a persistent VM disk image.
#
# Output: build/claw-os-vm.<fmt>  for each fmt in $FORMATS (default qcow2)
#
# Environment:
#   FORMATS  Space-separated output formats. Default: "qcow2".
#            Supported: qcow2, vmdk, vhdx, raw
#   SIZE     Virtual disk size. Default: "8G". Image is sparse, so the
#            actual file is much smaller (qcow2 typically ~2 GB for an
#            8 GB disk with stock claw-os contents).
#
# Disk layout (GPT, hybrid BIOS+UEFI bootable):
#   1MiB-2MiB     bios_grub          (raw, no fs)
#   2MiB-258MiB   ESP                (fat32, /boot/efi)
#   258MiB-100%   root               (ext4, /)
#
# Host requirements (Debian/Ubuntu):
#   apt install qemu-utils parted dosfstools rsync util-linux
#   (mkfs.ext4 is in e2fsprogs which is always installed)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
ROOTFS="$PROJECT_DIR/build/claw-os-rootfs"
BUILD_DIR="$PROJECT_DIR/build"
RAW="$BUILD_DIR/claw-os-vm.raw"
MNT="$BUILD_DIR/vm-mnt"

FORMATS="${FORMATS:-qcow2}"
SIZE="${SIZE:-8G}"

if [ "$(id -u)" -ne 0 ]; then
    echo "error: must run as root (losetup, mount, mkfs need it)" >&2
    exit 1
fi

# Host tooling.
missing=""
for tool in qemu-img parted mkfs.ext4 mkfs.vfat losetup rsync blkid; do
    command -v "$tool" >/dev/null 2>&1 || missing="$missing $tool"
done
if [ -n "$missing" ]; then
    echo "error: missing host tools:$missing" >&2
    echo "install: apt install qemu-utils parted dosfstools rsync util-linux" >&2
    exit 1
fi

# 1. Build the rootfs.
#    apt-source pre-configures the Claw OS apt repo so users can run
#    `sudo apt update && sudo apt upgrade` to pull newer claw-os-* packages.
#
#    FEATURES is overridable. Example, build a desktop VM image:
#       FEATURES=base,cos-core,systemd,kernel,desktop,grub-disk,vm,apt-source \
#       SIZE=16G FORMATS=vhdx ./targets/vm/build.sh
FEATURES="${FEATURES:-base,cos-core,systemd,kernel,grub-disk,vm,apt-source}"
echo ":: features: $FEATURES"
"$PROJECT_DIR/rootfs/build.sh" --features "$FEATURES"

# 2. Reset previous build artefacts.
rm -f "$RAW"
rm -rf "$MNT"
mkdir -p "$MNT"

# 3. Create raw disk + partition table.
echo ":: creating $SIZE raw image"
qemu-img create -f raw "$RAW" "$SIZE"

echo ":: partitioning (GPT: bios_grub + ESP + root)"
parted -s "$RAW" \
    mklabel gpt \
    mkpart bios_grub 1MiB 2MiB \
    set 1 bios_grub on \
    mkpart ESP fat32 2MiB 258MiB \
    set 2 esp on \
    mkpart root ext4 258MiB 100%

# 4. Attach as loop device with partition scanning so /dev/loopXp{1,2,3}
#    appear automatically. -P is essential — without it grub-probe inside
#    the chroot will fail to find the partition layout.
LOOP=$(losetup -Pf --show "$RAW")
echo ":: attached $RAW at $LOOP (with -P partitions: ${LOOP}p1 ${LOOP}p2 ${LOOP}p3)"

# Set up cleanup early so any failure unmounts and detaches.
cleanup() {
    set +e
    [ -d "$MNT" ] && umount -R "$MNT" 2>/dev/null
    [ -n "${LOOP:-}" ] && losetup -d "$LOOP" 2>/dev/null
}
trap cleanup EXIT

# Wait briefly for udev to settle (partition device nodes can lag).
for _ in 1 2 3 4 5; do
    [ -b "${LOOP}p2" ] && [ -b "${LOOP}p3" ] && break
    sleep 1
done
if [ ! -b "${LOOP}p3" ]; then
    echo "error: partition device ${LOOP}p3 not present — losetup -P likely failed" >&2
    exit 1
fi

# 5. Format.
echo ":: mkfs.vfat (ESP) on ${LOOP}p2"
mkfs.vfat -F32 -n ESP "${LOOP}p2"
echo ":: mkfs.ext4 (root) on ${LOOP}p3"
mkfs.ext4 -L ROOT -F "${LOOP}p3"

# 6. Mount target.
mount "${LOOP}p3" "$MNT"
mkdir -p "$MNT/boot/efi"
mount "${LOOP}p2" "$MNT/boot/efi"

# 7. Copy rootfs (preserve hardlinks, ACLs, xattrs; --numeric-ids keeps
#    file ownership stable across host UID schemes).
echo ":: rsync rootfs -> mounted image"
rsync -aHAX --numeric-ids "$ROOTFS/" "$MNT/"

# 8. Write /etc/fstab from blkid UUIDs (preserved through qemu-img convert).
ROOT_UUID=$(blkid -o value -s UUID "${LOOP}p3")
ESP_UUID=$(blkid -o value -s UUID "${LOOP}p2")
cat > "$MNT/etc/fstab" <<EOF
# /etc/fstab — generated by targets/vm/build.sh
UUID=$ROOT_UUID  /          ext4  defaults,errors=remount-ro  0  1
UUID=$ESP_UUID   /boot/efi  vfat  umask=0077                  0  1
EOF

# 9. Bind mounts for chroot grub-install.
#    /dev must be visible so grub-probe can scan /dev/loop*p* devices.
mount --rbind /dev  "$MNT/dev"
mount --rbind /sys  "$MNT/sys"
mount -t proc proc  "$MNT/proc"

# 10. Install GRUB for both BIOS and UEFI.
echo ":: grub-install --target=i386-pc $LOOP (BIOS)"
chroot "$MNT" grub-install --target=i386-pc "$LOOP"

echo ":: grub-install --target=x86_64-efi --removable --no-nvram (UEFI fallback path)"
# --removable writes to /EFI/BOOT/BOOTX64.EFI (the UEFI fallback that
# every firmware tries). --no-nvram skips efibootmgr — essential when
# building on a BIOS host or in a chroot without /sys/firmware/efi.
chroot "$MNT" grub-install \
    --target=x86_64-efi \
    --efi-directory=/boot/efi \
    --bootloader-id=claw-os \
    --removable \
    --no-nvram

echo ":: update-grub (writes /boot/grub/grub.cfg)"
chroot "$MNT" update-grub

# 11. Unwind.
sync
umount -R "$MNT"
losetup -d "$LOOP"
LOOP=""
trap - EXIT
rmdir "$MNT"

# 12. Convert raw -> requested formats. qemu-img convert preserves
#     filesystem UUIDs (block-level copy), so fstab UUID= entries stay
#     valid in every output. qcow2 is auto-sparse.
for fmt in $FORMATS; do
    case "$fmt" in
        raw)
            cp -a "$RAW" "$BUILD_DIR/claw-os-vm.raw.final"
            mv "$BUILD_DIR/claw-os-vm.raw.final" "$BUILD_DIR/claw-os-vm.raw"
            ;;
        qcow2|vmdk|vhdx)
            OUT="$BUILD_DIR/claw-os-vm.$fmt"
            echo ":: qemu-img convert -f raw -O $fmt -> $OUT"
            qemu-img convert -f raw -O "$fmt" -S 65536 "$RAW" "$OUT"
            ;;
        *)
            echo "warning: unknown format '$fmt', skipping" >&2
            ;;
    esac
done

# If only non-raw formats requested, drop the intermediate raw.
case " $FORMATS " in
    *" raw "*) : ;;
    *) rm -f "$RAW" ;;
esac

echo
echo ":: done"
ls -lh "$BUILD_DIR"/claw-os-vm.* 2>/dev/null

cat <<'EOF'

Test in QEMU (BIOS, default):
  qemu-system-x86_64 -m 2G -nographic \
      -drive file=build/claw-os-vm.qcow2,format=qcow2,if=virtio

Test in QEMU (UEFI, requires ovmf):
  qemu-system-x86_64 -m 2G -bios /usr/share/ovmf/OVMF.fd \
      -drive file=build/claw-os-vm.qcow2,format=qcow2,if=virtio

Hyper-V Gen 2 note:
  Gen 2 enables Secure Boot by default. Disable it before first boot:
    Set-VMFirmware -VMName claw-os -EnableSecureBoot Off
  Alternatively, attach to a Gen 1 VM (BIOS) — same .vhdx works.

VMware:
  Create a new VM, choose "I will install the OS later", point the
  existing virtual disk at build/claw-os-vm.vmdk.
EOF
