    use super::*;

    // ---- Cargo.lock ----

    #[test]
    fn cargo_lock_parses_two_packages() {
        let lock = r#"
# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "serde"
version = "1.0.219"

[[package]]
name = "tokio"
version = "1.43.0"
dependencies = ["bytes"]
"#;
        let pkgs = parse_cargo_lock(lock).expect("ok");
        assert_eq!(pkgs.len(), 2);
        assert_eq!(pkgs[0], Package::new("crates.io", "serde", "1.0.219"));
        assert_eq!(pkgs[1], Package::new("crates.io", "tokio", "1.43.0"));
    }

    #[test]
    fn cargo_lock_ignores_metadata_block() {
        let lock = r#"[[package]]
name = "foo"
version = "0.1.0"

[metadata]
foo = "bar"
"#;
        let pkgs = parse_cargo_lock(lock).expect("ok");
        assert_eq!(pkgs.len(), 1);
        assert_eq!(pkgs[0].name, "foo");
    }

    #[test]
    fn cargo_lock_handles_trailing_comment_in_value() {
        let lock = r#"[[package]]
name = "foo" # comment
version = "0.1.0" # other
"#;
        let pkgs = parse_cargo_lock(lock).expect("ok");
        assert_eq!(pkgs.len(), 1);
        assert_eq!(pkgs[0].name, "foo");
        assert_eq!(pkgs[0].version, "0.1.0");
    }

    #[test]
    fn cargo_lock_empty_returns_empty() {
        let pkgs = parse_cargo_lock("").expect("ok");
        assert!(pkgs.is_empty());
    }

    // ---- package-lock.json ----

    #[test]
    fn package_lock_v3_packages_format() {
        let body = r#"{
  "name": "myapp",
  "lockfileVersion": 3,
  "packages": {
    "": { "name": "myapp", "version": "1.0.0" },
    "node_modules/lodash": { "version": "4.17.21" },
    "node_modules/react": { "version": "18.2.0" }
  }
}"#;
        let pkgs = parse_package_lock_json(body).expect("ok");
        assert_eq!(pkgs.len(), 2);
        assert!(pkgs
            .iter()
            .any(|p| p.name == "lodash" && p.version == "4.17.21"));
        assert!(pkgs
            .iter()
            .any(|p| p.name == "react" && p.version == "18.2.0"));
        for p in &pkgs {
            assert_eq!(p.ecosystem, "npm");
        }
    }

    #[test]
    fn package_lock_v1_dependencies_format() {
        let body = r#"{
  "name": "old",
  "lockfileVersion": 1,
  "dependencies": {
    "lodash": { "version": "4.17.21" },
    "axios":  { "version": "1.7.2", "dependencies": {
      "follow-redirects": { "version": "1.15.6" }
    }}
  }
}"#;
        let pkgs = parse_package_lock_json(body).expect("ok");
        assert!(pkgs.iter().any(|p| p.name == "lodash"));
        assert!(pkgs.iter().any(|p| p.name == "axios"));
        assert!(pkgs.iter().any(|p| p.name == "follow-redirects"));
    }

    #[test]
    fn package_lock_dedupes_same_name_version() {
        let body = r#"{
  "lockfileVersion": 3,
  "packages": {
    "node_modules/lodash": { "version": "4.17.21" },
    "node_modules/foo/node_modules/lodash": { "version": "4.17.21" }
  }
}"#;
        let pkgs = parse_package_lock_json(body).expect("ok");
        assert_eq!(pkgs.iter().filter(|p| p.name == "lodash").count(), 1);
    }

    #[test]
    fn package_lock_invalid_json_errors() {
        let err = parse_package_lock_json("not json").unwrap_err();
        assert!(err.contains("package-lock"));
    }

    // ---- requirements.txt ----

    #[test]
    fn requirements_parses_pin_lines() {
        let body = "django==4.2.0\nrequests==2.32.0\n";
        let pkgs = parse_requirements_txt(body);
        assert_eq!(pkgs.len(), 2);
        assert_eq!(pkgs[0], Package::new("PyPI", "django", "4.2.0"));
    }

    #[test]
    fn requirements_skips_loose_specifiers_and_comments() {
        let body = "# header\nflask>=2.0\nclick~=8.0\nrequests==2.32.0\n-r dev.txt\n";
        let pkgs = parse_requirements_txt(body);
        assert_eq!(pkgs.len(), 1);
        assert_eq!(pkgs[0].name, "requests");
    }

    #[test]
    fn requirements_strips_extras_and_markers() {
        let body = "uvicorn[standard]==0.30.0 ; python_version >= '3.10'\n";
        let pkgs = parse_requirements_txt(body);
        assert_eq!(pkgs.len(), 1);
        assert_eq!(pkgs[0].name, "uvicorn");
        assert_eq!(pkgs[0].version, "0.30.0");
    }

    #[test]
    fn requirements_ignores_inline_comments() {
        let body = "django==4.2.0  # latest LTS\n";
        let pkgs = parse_requirements_txt(body);
        assert_eq!(pkgs.len(), 1);
    }

    // ---- go.sum ----

    #[test]
    fn go_sum_parses_module_lines() {
        let body = "github.com/stretchr/testify v1.10.0 h1:Xv5erBjTwe/5IxqUQTdXv5kgmIvbHo3QQyRwhJsOfJA=\n\
                    github.com/stretchr/testify v1.10.0/go.mod h1:r2ic/lqez/lEtzL7wO/rwa5dbSLXVDPFyf8C91i36aY=\n\
                    rsc.io/quote v1.5.2 h1:wWYsXxXc8DrGdAxwM6IhGXowD9o0pNdLg7njVcRQc/8=\n";
        let pkgs = parse_go_sum(body);
        assert_eq!(pkgs.len(), 2);
        let mut names: Vec<&str> = pkgs.iter().map(|p| p.name.as_str()).collect();
        names.sort();
        assert_eq!(names, vec!["github.com/stretchr/testify", "rsc.io/quote"]);
        for p in &pkgs {
            assert_eq!(p.ecosystem, "Go");
            assert!(!p.version.contains("/go.mod"));
        }
    }

    #[test]
    fn go_sum_skips_blank_lines() {
        let body = "\n\nrsc.io/quote v1.5.2 h1:abc\n\n";
        let pkgs = parse_go_sum(body);
        assert_eq!(pkgs.len(), 1);
    }

    // ---- parse_lockfile dispatch ----

    #[test]
    fn parse_lockfile_routes_by_filename() {
        let p = parse_lockfile(
            Path::new("Cargo.lock"),
            "[[package]]\nname = \"foo\"\nversion = \"0.1.0\"\n",
        )
        .expect("ok");
        assert_eq!(p.len(), 1);
        assert_eq!(p[0].ecosystem, "crates.io");
    }

    #[test]
    fn parse_lockfile_case_insensitive_filename() {
        let p = parse_lockfile(
            Path::new("CARGO.LOCK"),
            "[[package]]\nname = \"foo\"\nversion = \"0.1.0\"\n",
        )
        .expect("ok");
        assert_eq!(p.len(), 1);
    }

    #[test]
    fn parse_lockfile_unknown_filename_errs() {
        let err = parse_lockfile(Path::new("Pipfile.lock"), "{}").unwrap_err();
        assert!(err.contains("unknown lockfile"));
    }

    // ---- parse_query_response ----

    #[test]
    fn parse_response_empty_returns_empty_vec() {
        let v: Value = serde_json::from_str("{}").unwrap();
        assert!(parse_query_response(&v).unwrap().is_empty());
    }

    #[test]
    fn parse_response_null_vulns_returns_empty_vec() {
        let v: Value = serde_json::from_str(r#"{"vulns": null}"#).unwrap();
        assert!(parse_query_response(&v).unwrap().is_empty());
    }

    #[test]
    fn parse_response_extracts_id_and_summary() {
        let body = r#"{
  "vulns": [
    {
      "id": "GHSA-xxxx-yyyy-zzzz",
      "summary": "Cross-site scripting in foo",
      "aliases": ["CVE-2024-12345"],
      "modified": "2024-05-01T00:00:00Z",
      "published": "2024-04-15T00:00:00Z",
      "references": [
        { "type": "ADVISORY", "url": "https://example.com/a" }
      ]
    }
  ]
}"#;
        let v: Value = serde_json::from_str(body).unwrap();
        let vulns = parse_query_response(&v).expect("ok");
        assert_eq!(vulns.len(), 1);
        let vuln = &vulns[0];
        assert_eq!(vuln.id, "GHSA-xxxx-yyyy-zzzz");
        assert_eq!(vuln.summary.as_deref(), Some("Cross-site scripting in foo"));
        assert_eq!(vuln.aliases, vec!["CVE-2024-12345"]);
        assert_eq!(vuln.references.len(), 1);
        assert_eq!(vuln.references[0].kind, "ADVISORY");
    }

    #[test]
    fn parse_response_rejects_non_array_vulns() {
        let v: Value = serde_json::from_str(r#"{"vulns": "oops"}"#).unwrap();
        let err = parse_query_response(&v).unwrap_err();
        assert!(err.contains("array"));
    }

    // ---- Package json round-trip ----

    #[test]
    fn package_to_json_round_trips() {
        let p = Package::new("npm", "lodash", "4.17.21");
        let v = p.to_json();
        assert_eq!(v.get("ecosystem").and_then(|s| s.as_str()), Some("npm"));
        assert_eq!(v.get("name").and_then(|s| s.as_str()), Some("lodash"));
        assert_eq!(v.get("version").and_then(|s| s.as_str()), Some("4.17.21"));
    }
