// DO NOT EDIT BY HAND.
// Generated by claw-os-sdk/wire/codegen.py from wire/v1/*.schema.json.
// Run `python3 wire/codegen.py` from the SDK root to regenerate.

/* eslint-disable */

export const EXPECTED_WIRE_VERSION = 1 as const;


/**
 * AI request / reply.
 * Stable text-chat reply returned by `cos ai chat`.
 */
export interface Ai {
  text: string;
  model: string;
  provider: string;
  verb: "ai.chat" | "ai.chat.untrusted";
  usage: AiUsage;
  budget: AiBudget;
  review: AiReview;
  tool_calls?: AiToolCall[];
}

/**
 * ai_usage.
 * Token and unit accounting for this call.
 */
export interface AiUsage {
  input_tokens: number;
  output_tokens: number;
  units: number;
}

/**
 * ai_budget.
 * App budget snapshot after the call.
 */
export interface AiBudget {
  period: string;
  units_used: number;
  units_cap: number;
}

/**
 * ai_review.
 * Safety policy actually applied by the kernel.
 */
export interface AiReview {
  safety: "strict" | "standard" | "minimal";
  prompt_redacted: boolean;
}

/**
 * AiToolCall.
 */
export interface AiToolCall {
  id: string;
  name: string;
  input: unknown;
}

/**
 * App-verb invocation reply.
 * Reply shape for `cos app <id> <verb> [args]`. The payload is the verb's own
 * JSON output — what schema you get depends on which verb you called. The
 * kernel guarantees only that the body is valid JSON (or stderr-routed when
 * stdout would be ambiguous).
 */
export interface App {
  verb?: string;
  app?: string;
}

/**
 * Envelope.
 * Common wrapper around every wire v1 reply. Forward-compatible target shape —
 * the current kernel still emits flat per-command shapes that SDKs adapt to
 * this envelope.
 */
export interface Envelope {
  ok: boolean;
  wire_version: 1;
  audit_id?: string;
  data?: Record<string, unknown>;
  error?: string;
  code?: string;
  detail?: Record<string, unknown>;
}

/**
 * App manifest (app.json).
 * The manifest every app under COS_APPS_DIR must provide. The kernel parses
 * and validates this (core/src/caps/manifest.rs) to derive the app's
 * operations, optional MCP session tools, optional desktop GUI surface,
 * capability needs, and AI policy.
 */
export interface Manifest {
  id: string;
  version: string;
  name: Localizedtext;
  summary?: Localizedtext;
  icon?: string;
  runtime?: "python" | "node" | "shell" | "binary";
  entry?: string;
  operations?: Record<string, unknown>;
  ai?: Aipolicy;
  session?: Session;
  desktop?: Desktop;
  dependencies?: Record<string, unknown>;
}

/**
 * localizedText.
 * Localized string map. The `en` key is required; other locales (zh-CN, ...)
 * are optional fallbacks.
 */
export interface Localizedtext {
  en: string;
}

/**
 * operation.
 * A one-shot operation: its inputs and the capabilities it needs.
 */
export interface Operation {
  label: Localizedtext;
  summary?: Localizedtext;
  args?: Arg[];
  needs?: Need[];
}

/**
 * arg.
 */
export interface Arg {
  name: string;
  kind: "path" | "host" | "name" | "text" | "number" | "bool";
  required?: boolean;
  default?: unknown;
  label?: Localizedtext;
}

/**
 * need.
 * A single capability request: verb + scope binding + human reason.
 */
export interface Need {
  verb: "fs.read" | "fs.write" | "fs.delete" | "fs.exec" | "fs.watch" | "fs.meta" | "net.dial" | "net.listen" | "net.raw" | "net.resolve" | "proc.spawn" | "proc.signal" | "proc.observe" | "sys.observe" | "sys.service" | "sys.package" | "sys.mount" | "sys.time" | "sys.power" | "sys.kernel" | "secret.read" | "secret.write" | "secret.grant" | "agent.spawn" | "agent.invoke" | "agent.observe" | "agent.delegate" | "data.kv.read" | "data.kv.write" | "data.kv.delete" | "data.db.read" | "data.db.write" | "data.log.read" | "data.log.write" | "data.inbox.read" | "data.inbox.write" | "memory.write" | "memory.read" | "ipc.publish" | "ipc.subscribe" | "ipc.invoke" | "ui.notify" | "ui.prompt" | "ui.window" | "ui.input" | "clipboard.read" | "clipboard.write" | "device.audio" | "device.camera" | "device.microphone" | "device.location" | "device.sensor" | "device.usb" | "time.cron" | "time.delay" | "ai.chat" | "ai.chat.untrusted" | "desktop.launch" | "browser.tabs.read" | "browser.nav" | "browser.dom.read" | "browser.dom.write" | "browser.input.secret" | "browser.eval";
  scope: Scopebinding;
  why: Localizedtext;
}

/**
 * scopeBinding.
 * How an operation's scope is determined at invocation time. kind=from-arg
 * reads a named arg at call time; kind=fixed hard-codes a scope; kind=wild is
 * an explicit wildcard (no implicit '*').
 */
export interface Scopebinding {
  kind: "from-arg" | "fixed" | "wild";
  arg?: string;
  scope?: Scope;
}

/**
 * scope.
 * A concrete capability scope. value is a glob for path/host/name, the self-
 * reference string for self-ref, and absent for wild.
 */
export interface Scope {
  kind: "path" | "host" | "name" | "self-ref" | "wild";
  value?: string;
}

/**
 * aiPolicy.
 * Budget + safety envelope under which the app may exercise ai.* verbs. Apps
 * never pick the model; the OS owns the provider.
 */
export interface Aipolicy {
  budget: Aibudget;
  safety?: "strict" | "standard" | "minimal";
  origins?: "trusted" | "user-input" | "external-content"[];
  tools?: string[];
}

/**
 * aiBudget.
 */
export interface Aibudget {
  monthly_units?: number;
}

/**
 * session.
 * Long-lived MCP server the app launches for stateful, agent-driven tool
 * calls.
 */
export interface Session {
  entry?: string;
  transport?: "stdio";
  tools?: Sessiontool[];
}

/**
 * sessionTool.
 * One MCP-callable tool. Mirrors operation: args + needs drive the model's
 * view and the kernel's enforcement.
 */
export interface Sessiontool {
  name: string;
  summary: Localizedtext;
  args?: Arg[];
  needs?: Need[];
}

/**
 * desktop.
 * Desktop GUI surface. Drives generation of
 * /usr/share/applications/com.clawos.<Id>.desktop at install time.
 */
export interface Desktop {
  exec?: string;
  name?: Localizedtext;
  icon?: string;
  categories?: string[];
  mime_types?: string[];
  single_instance?: boolean;
  panel_applet?: boolean;
}

/**
 * Permissions request / reply.
 * Shape of the success-path data field returned by policy checks. Apps call
 * this via SDK helpers (e.g. cos_runtime.policy.check).
 */
export interface Perms {
  decision: "allow" | "deny" | "prompt";
  verb: string;
  scope?: unknown;
  reason?: string;
  hint?: string;
  granted?: boolean;
}

/**
 * Catalog tool invocation reply.
 * Shape returned by `cos ai tool <name> --app <id> --args '<json>'`.
 */
export interface Tool {
  tool: string;
  app_id: string;
  status: "ok";
  result: unknown;
}

