// DO NOT EDIT BY HAND.
// Generated by claw-os-sdk/wire/codegen.py from wire/v1/*.schema.json.
// Run `python3 wire/codegen.py` from the SDK root to regenerate.

/* eslint-disable */


/**
 * AI request / reply.
 * Shape of the data payload returned by `cos ai chat|embed|image-generate`.
 * Apps call this via SDK helpers (claw_os_sdk.ai.chat / ai.embed /
 * ai.image_generate). The kernel emits the same fields whether the call was
 * synchronous or streamed (terminating reply).
 */
export interface Ai {
  verb: "ai.chat" | "ai.embed" | "ai.image_generate" | "ai.tool";
  text?: string;
  model?: string;
  provider?: string;
  embedding?: number[];
  embeddings?: number[][];
  output_path?: string;
  usage?: AiUsage;
  budget?: AiBudget;
  review?: AiReview;
  tool_calls?: AiToolCalls[];
  raw?: unknown;
}

/**
 * ai_usage.
 * Token / unit accounting for this single call.
 */
export interface AiUsage {
  input_tokens?: number;
  output_tokens?: number;
  units?: number;
}

/**
 * ai_budget.
 * Snapshot of the app's budget *after* this call.
 */
export interface AiBudget {
  period?: string;
  units_used?: number;
  units_cap?: number;
}

/**
 * ai_review.
 * Safety / review metadata.
 */
export interface AiReview {
  safety?: "strict" | "balanced" | "off";
  prompt_redacted?: boolean;
  response_blocked?: boolean;
}

/**
 * ai_tool_calls.
 */
export interface AiToolCalls {
  name: string;
  args?: Record<string, unknown>;
  result?: unknown;
}

/**
 * App-verb invocation reply.
 * Reply shape for `cos app <id> <verb> [args]`. The payload is the verb's own
 * JSON output — what schema you get depends on which verb you called. The
 * kernel guarantees only that the body is valid JSON (or stderr-routed when
 * stdout would be ambiguous).
 */
export interface App {
  verb?: string;
  app?: string;
}

/**
 * Envelope.
 * Common wrapper around every wire v1 reply. Forward-compatible target shape —
 * the current kernel still emits flat per-command shapes that SDKs adapt to
 * this envelope.
 */
export interface Envelope {
  ok: boolean;
  wire_version: 1;
  audit_id?: string;
  data?: Record<string, unknown>;
  error?: string;
  code?: string;
  detail?: Record<string, unknown>;
}

/**
 * App manifest (app.json).
 * The manifest every app under COS_APPS_DIR must provide. The kernel validates
 * and uses this to derive declared verbs, runtime, and capability
 * requirements.
 */
export interface Manifest {
  id: string;
  name: string;
  version?: string;
  runtime: "python" | "binary" | "node" | "go";
  entry?: string;
  verbs: ManifestVerbs[];
}

/**
 * manifest_verbs.
 */
export interface ManifestVerbs {
  name: string;
  summary?: string;
  args?: Arg[];
  needs?: Caprequest[];
  side_effects?: boolean;
}

/**
 * arg.
 */
export interface Arg {
  name: string;
  kind: "path" | "host" | "name" | "text";
  required?: boolean;
}

/**
 * capRequest.
 */
export interface Caprequest {
  verb: string;
  scope?: unknown;
}

/**
 * Permissions request / reply.
 * Shape of the success-path data field returned by `cos perms check`. Apps
 * call this via SDK helpers (e.g. cos_runtime.policy.check).
 */
export interface Perms {
  decision: "allow" | "deny" | "prompt";
  verb: string;
  scope?: unknown;
  reason?: string;
  hint?: string;
  granted?: boolean;
}

/**
 * Catalog tool invocation reply.
 * Shape returned by `cos ai tool <name> --app <id> --args '<json>'`. Catalog
 * tools are reusable functions exposed in the AI tool catalog. They differ
 * from app verbs in that the AI plans them automatically.
 */
export interface Tool {
  tool: string;
  result?: unknown;
  audit_id?: string;
}

