"""DO NOT EDIT BY HAND.
Generated by claw-os-sdk/wire/codegen.py from wire/v1/*.schema.json.
Run `python3 wire/codegen.py` from the SDK root to regenerate.
"""

from __future__ import annotations

from typing import Any, Dict, List, TypedDict


class Ai(TypedDict, total=False):
    """AI request / reply.

    Shape of the data payload returned by `cos ai chat|embed|image-generate`.
    Apps call this via SDK helpers (claw_os_sdk.ai.chat / ai.embed /
    ai.image_generate). The kernel emits the same fields whether the call was
    synchronous or streamed (terminating reply).
    """
    verb: str  # required
    text: str
    model: str
    provider: str
    embedding: List[float]
    embeddings: List[List[float]]
    output_path: str
    usage: "AiUsage"
    budget: "AiBudget"
    review: "AiReview"
    tool_calls: List["AiToolCalls"]
    raw: Any

class AiUsage(TypedDict, total=False):
    """ai_usage.

    Token / unit accounting for this single call.
    """
    input_tokens: int
    output_tokens: int
    units: float

class AiBudget(TypedDict, total=False):
    """ai_budget.

    Snapshot of the app's budget *after* this call.
    """
    period: str
    units_used: float
    units_cap: float

class AiReview(TypedDict, total=False):
    """ai_review.

    Safety / review metadata.
    """
    safety: str
    prompt_redacted: bool
    response_blocked: bool

class AiToolCalls(TypedDict, total=False):
    """ai_tool_calls.
    """
    name: str  # required
    args: Dict[str, Any]
    result: Any

class App(TypedDict, total=False):
    """App-verb invocation reply.

    Reply shape for `cos app <id> <verb> [args]`. The payload is the verb's own
    JSON output — what schema you get depends on which verb you called. The
    kernel guarantees only that the body is valid JSON (or stderr-routed when
    stdout would be ambiguous).
    """
    verb: str
    app: str

class Envelope(TypedDict, total=False):
    """Envelope.

    Common wrapper around every wire v1 reply. Forward-compatible target shape —
    the current kernel still emits flat per-command shapes that SDKs adapt to
    this envelope.
    """
    ok: bool  # required
    wire_version: int  # required
    audit_id: str
    data: Dict[str, Any]
    error: str
    code: str
    detail: Dict[str, Any]

class Manifest(TypedDict, total=False):
    """App manifest (app.json).

    The manifest every app under COS_APPS_DIR must provide. The kernel validates
    and uses this to derive declared verbs, runtime, and capability
    requirements.
    """
    id: str  # required
    name: str  # required
    version: str
    runtime: str  # required
    entry: str
    verbs: List["ManifestVerbs"]  # required

class ManifestVerbs(TypedDict, total=False):
    """manifest_verbs.
    """
    name: str  # required
    summary: str
    args: List["Arg"]
    needs: List["Caprequest"]
    side_effects: bool

class Arg(TypedDict, total=False):
    """arg.
    """
    name: str  # required
    kind: str  # required
    required: bool

class Caprequest(TypedDict, total=False):
    """capRequest.
    """
    verb: str  # required
    scope: Any

class Perms(TypedDict, total=False):
    """Permissions request / reply.

    Shape of the success-path data field returned by `cos perms check`. Apps
    call this via SDK helpers (e.g. cos_runtime.policy.check).
    """
    decision: str  # required
    verb: str  # required
    scope: Any
    reason: str
    hint: str
    granted: bool

class Tool(TypedDict, total=False):
    """Catalog tool invocation reply.

    Shape returned by `cos ai tool <name> --app <id> --args '<json>'`. Catalog
    tools are reusable functions exposed in the AI tool catalog. They differ
    from app verbs in that the AI plans them automatically.
    """
    tool: str  # required
    result: Any
    audit_id: str

