// DO NOT EDIT BY HAND.
// Generated by claw-os-sdk/wire/codegen.py from wire/v1/*.schema.json.
// Run `python3 wire/codegen.py` from the SDK root to regenerate.

#![allow(clippy::all)]
#![allow(non_snake_case, non_camel_case_types)]

use serde_json;

/// AI request / reply
/// Shape of the data payload returned by `cos ai chat|embed|image-generate`. Apps
/// call this via SDK helpers (claw_os_sdk.ai.chat / ai.embed /
/// ai.image_generate). The kernel emits the same fields whether the call was
/// synchronous or streamed (terminating reply).
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct Ai {
    pub verb: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub text: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub provider: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub embedding: Option<Vec<f64>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub embeddings: Option<Vec<Vec<f64>>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub output_path: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub usage: Option<AiUsage>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub budget: Option<AiBudget>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub review: Option<AiReview>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tool_calls: Option<Vec<AiToolCalls>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub raw: Option<serde_json::Value>,
}

/// ai_usage
/// Token / unit accounting for this single call.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct AiUsage {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub input_tokens: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub output_tokens: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub units: Option<f64>,
}

/// ai_budget
/// Snapshot of the app's budget *after* this call.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct AiBudget {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub period: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub units_used: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub units_cap: Option<f64>,
}

/// ai_review
/// Safety / review metadata.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct AiReview {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub safety: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub prompt_redacted: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub response_blocked: Option<bool>,
}

/// ai_tool_calls
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct AiToolCalls {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub args: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub result: Option<serde_json::Value>,
}

/// App-verb invocation reply
/// Reply shape for `cos app <id> <verb> [args]`. The payload is the verb's own
/// JSON output — what schema you get depends on which verb you called. The kernel
/// guarantees only that the body is valid JSON (or stderr-routed when stdout
/// would be ambiguous).
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct App {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub verb: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub app: Option<String>,
}

/// Envelope
/// Common wrapper around every wire v1 reply. Forward-compatible target shape —
/// the current kernel still emits flat per-command shapes that SDKs adapt to this
/// envelope.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct Envelope {
    pub ok: bool,
    pub wire_version: u8,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub audit_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub data: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub detail: Option<serde_json::Value>,
}

/// App manifest (app.json)
/// The manifest every app under COS_APPS_DIR must provide. The kernel validates
/// and uses this to derive declared verbs, runtime, and capability requirements.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct Manifest {
    pub id: String,
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    pub runtime: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub entry: Option<String>,
    pub verbs: Vec<ManifestVerbs>,
}

/// manifest_verbs
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ManifestVerbs {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub summary: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub args: Option<Vec<Arg>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub needs: Option<Vec<Caprequest>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub side_effects: Option<bool>,
}

/// arg
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct Arg {
    pub name: String,
    pub kind: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub required: Option<bool>,
}

/// capRequest
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct Caprequest {
    pub verb: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub scope: Option<serde_json::Value>,
}

/// Permissions request / reply
/// Shape of the success-path data field returned by `cos perms check`. Apps call
/// this via SDK helpers (e.g. claw_os_sdk.policy.check).
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct Perms {
    pub decision: String,
    pub verb: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub scope: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub hint: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub granted: Option<bool>,
}

/// Catalog tool invocation reply
/// Shape returned by `cos ai tool <name> --app <id> --args '<json>'`. Catalog
/// tools are reusable functions exposed in the AI tool catalog. They differ from
/// app verbs in that the AI plans them automatically.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct Tool {
    pub tool: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub result: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub audit_id: Option<String>,
}

