//! Static asset serving — the embedded Vite-built React SPA.
//!
//! The bundle lives at `core/src/agent/web/ui/dist/` (committed to git
//! to avoid making `bun` a `cargo build` prerequisite) and is folded
//! into the `cos` binary at compile time with [`include_dir!`]. So
//! `cos agent serve` still ships as a single self-contained executable,
//! exactly like the old single-file SPA — only now the SPA is a real
//! React + Tailwind v4 + Radix UI application generated by Vite, with
//! its visual language ported verbatim from `open-agents` (oklch dark
//! tokens, sidebar+inset layout, shadcn primitives).
//!
//! See `core/src/agent/web/ui/README.md` for the build instructions if
//! you need to refresh `dist/` after changing the UI sources.

use axum::extract::Path;
use axum::http::{header, HeaderValue, StatusCode};
use axum::response::{IntoResponse, Response};
use include_dir::{include_dir, Dir};

static UI_DIR: Dir<'_> = include_dir!("$CARGO_MANIFEST_DIR/src/agent/web/ui/dist");

fn mime_for(path: &str) -> &'static str {
    let ext = path.rsplit('.').next().unwrap_or("").to_ascii_lowercase();
    match ext.as_str() {
        "html" => "text/html; charset=utf-8",
        "js" | "mjs" => "application/javascript; charset=utf-8",
        "css" => "text/css; charset=utf-8",
        "json" => "application/json; charset=utf-8",
        "svg" => "image/svg+xml",
        "png" => "image/png",
        "jpg" | "jpeg" => "image/jpeg",
        "ico" => "image/x-icon",
        "woff" => "font/woff",
        "woff2" => "font/woff2",
        "ttf" => "font/ttf",
        "map" => "application/json; charset=utf-8",
        "txt" => "text/plain; charset=utf-8",
        _ => "application/octet-stream",
    }
}

fn cache_control_for(path: &str) -> &'static str {
    // Vite emits hashed filenames into `assets/`; those are safe to
    // cache forever. Everything else (index.html, favicon) must revalidate.
    if path.starts_with("assets/") {
        "public, max-age=31536000, immutable"
    } else {
        "no-store"
    }
}

fn serve_file(path: &str) -> Response {
    let Some(file) = UI_DIR.get_file(path) else {
        return (StatusCode::NOT_FOUND, "not found").into_response();
    };
    let mut resp = (StatusCode::OK, file.contents().to_vec()).into_response();
    resp.headers_mut().insert(
        header::CONTENT_TYPE,
        HeaderValue::from_static(mime_for(path)),
    );
    resp.headers_mut().insert(
        header::CACHE_CONTROL,
        HeaderValue::from_static(cache_control_for(path)),
    );
    resp
}

pub async fn index() -> Response {
    serve_file("index.html")
}

pub async fn favicon() -> Response {
    if UI_DIR.get_file("favicon.png").is_some() {
        return serve_file("favicon.png");
    }
    if UI_DIR.get_file("favicon.ico").is_some() {
        return serve_file("favicon.ico");
    }
    // Fall back to a 1x1 transparent PNG so we never emit a 404 on the
    // browser's automatic favicon fetch.
    const PIXEL: &[u8] = &[
        0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A, 0x00, 0x00, 0x00, 0x0D, 0x49, 0x48, 0x44,
        0x52, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x01, 0x08, 0x06, 0x00, 0x00, 0x00, 0x1F,
        0x15, 0xC4, 0x89, 0x00, 0x00, 0x00, 0x0D, 0x49, 0x44, 0x41, 0x54, 0x78, 0x9C, 0x63, 0x00,
        0x01, 0x00, 0x00, 0x05, 0x00, 0x01, 0x0D, 0x0A, 0x2D, 0xB4, 0x00, 0x00, 0x00, 0x00, 0x49,
        0x45, 0x4E, 0x44, 0xAE, 0x42, 0x60, 0x82,
    ];
    let mut resp = (StatusCode::OK, PIXEL.to_vec()).into_response();
    resp.headers_mut()
        .insert(header::CONTENT_TYPE, HeaderValue::from_static("image/png"));
    resp.headers_mut().insert(
        header::CACHE_CONTROL,
        HeaderValue::from_static("public, max-age=86400"),
    );
    resp
}

/// Brand assets emitted by Vite into `public/`, served at the bundle root.
/// `assets::asset` only handles `assets/<file>`; the public-folder files
/// need their own handlers.
pub async fn brand_symbol_light() -> Response {
    serve_file("clawos-symbol.png")
}

pub async fn brand_symbol_dark() -> Response {
    serve_file("clawos-symbol-dark.png")
}

/// Catch-all for `/assets/<file>` — serves hashed Vite chunks.
pub async fn asset(Path(file): Path<String>) -> Response {
    // Reject path-traversal probes. include_dir only honours plain
    // paths anyway, but be defensive.
    if file.contains("..") || file.contains('\\') {
        return (StatusCode::BAD_REQUEST, "bad path").into_response();
    }
    let key = format!("assets/{}", file);
    serve_file(&key)
}
