/**
 * A curated list of ~200 notable cities from across the globe.
 * Used to assign memorable, unique session names.
 */
const CITIES: string[] = [
  // Africa
  "Abidjan",
  "Accra",
  "Addis Ababa",
  "Algiers",
  "Antananarivo",
  "Cairo",
  "Cape Town",
  "Casablanca",
  "Dakar",
  "Dar es Salaam",
  "Johannesburg",
  "Kampala",
  "Kigali",
  "Kinshasa",
  "Lagos",
  "Luanda",
  "Lusaka",
  "Maputo",
  "Marrakech",
  "Nairobi",
  "Tunis",
  "Windhoek",

  // Asia
  "Almaty",
  "Amman",
  "Baku",
  "Bangkok",
  "Beijing",
  "Beirut",
  "Bengaluru",
  "Bishkek",
  "Colombo",
  "Dhaka",
  "Dubai",
  "Hanoi",
  "Ho Chi Minh City",
  "Hong Kong",
  "Hyderabad",
  "Islamabad",
  "Istanbul",
  "Jakarta",
  "Jeddah",
  "Jerusalem",
  "Kabul",
  "Karachi",
  "Kathmandu",
  "Kolkata",
  "Kuala Lumpur",
  "Kyoto",
  "Manila",
  "Mumbai",
  "Muscat",
  "New Delhi",
  "Osaka",
  "Phnom Penh",
  "Riyadh",
  "Seoul",
  "Shanghai",
  "Shenzhen",
  "Singapore",
  "Taipei",
  "Tashkent",
  "Tbilisi",
  "Tehran",
  "Tel Aviv",
  "Thimphu",
  "Tokyo",
  "Ulaanbaatar",
  "Vientiane",
  "Yangon",
  "Yerevan",

  // Europe
  "Amsterdam",
  "Athens",
  "Barcelona",
  "Belgrade",
  "Berlin",
  "Bern",
  "Bordeaux",
  "Bratislava",
  "Brussels",
  "Bucharest",
  "Budapest",
  "Copenhagen",
  "Dublin",
  "Edinburgh",
  "Florence",
  "Geneva",
  "Hamburg",
  "Helsinki",
  "Kraków",
  "Kyiv",
  "Lisbon",
  "Ljubljana",
  "London",
  "Lyon",
  "Madrid",
  "Marseille",
  "Milan",
  "Minsk",
  "Monaco",
  "Moscow",
  "Munich",
  "Naples",
  "Oslo",
  "Paris",
  "Porto",
  "Prague",
  "Reykjavik",
  "Riga",
  "Rome",
  "Sarajevo",
  "Seville",
  "Sofia",
  "Stockholm",
  "Tallinn",
  "Valencia",
  "Venice",
  "Vienna",
  "Vilnius",
  "Warsaw",
  "Zagreb",
  "Zurich",

  // North America
  "Anchorage",
  "Atlanta",
  "Austin",
  "Boston",
  "Calgary",
  "Chicago",
  "Denver",
  "Detroit",
  "Guadalajara",
  "Havana",
  "Honolulu",
  "Houston",
  "Kingston",
  "Los Angeles",
  "Mexico City",
  "Miami",
  "Minneapolis",
  "Montreal",
  "Nashville",
  "New Orleans",
  "New York",
  "Ottawa",
  "Philadelphia",
  "Phoenix",
  "Portland",
  "San Diego",
  "San Francisco",
  "San Juan",
  "Seattle",
  "Toronto",
  "Vancouver",
  "Washington",

  // South America
  "Bogotá",
  "Brasília",
  "Buenos Aires",
  "Caracas",
  "Cartagena",
  "Cusco",
  "Guayaquil",
  "La Paz",
  "Lima",
  "Medellín",
  "Montevideo",
  "Quito",
  "Recife",
  "Rio de Janeiro",
  "Santiago",
  "São Paulo",
  "Valparaíso",

  // Oceania
  "Adelaide",
  "Auckland",
  "Brisbane",
  "Christchurch",
  "Fiji",
  "Melbourne",
  "Perth",
  "Sydney",
  "Wellington",
];

/**
 * Pick a random city name that hasn't been used yet by this user.
 *
 * @param usedNames - Set of session titles the user already has.
 * @returns A city name not in `usedNames`, or a numbered fallback
 *          (e.g. "Tokyo 2") if all cities have been used.
 */
export function getRandomCityName(usedNames: Set<string>): string {
  // Filter to cities not yet used
  const available = CITIES.filter((city) => !usedNames.has(city));

  if (available.length > 0) {
    return available[Math.floor(Math.random() * available.length)]!;
  }

  // All cities exhausted — pick a random city and append a number
  const base = CITIES[Math.floor(Math.random() * CITIES.length)]!;
  let suffix = 2;
  while (usedNames.has(`${base} ${suffix}`)) {
    suffix++;
  }
  return `${base} ${suffix}`;
}
