appid := env_var('APPID')
install-dir := env_var('INSTALL_DIR')

icons-src := 'hicolor'
icons-dst := install-dir / 'icons' / 'hicolor'

install:
    for size in `ls {{icons-src}}`; do \
        install -Dm0644 "{{icons-src}}/$size/apps/{{appid}}.png" "{{icons-dst}}/$size/apps/{{appid}}.png"; \
    done


uninstall:
    for size in `ls {{icons-src}}`; do \
        rm -f "{{icons-dst}}/$size/apps/{{appid}}.png"; \
    done
