#!/usr/bin/env bash
# tools/install-mail-ai.sh
#
# Install the Claw Mail AI WebExtension and its Native Messaging host
# system-wide for the locally installed Thunderbird.
#
#   - WebExtension source       → /usr/share/claw/extensions/claw-mail-ai/
#   - Thunderbird policies      → /etc/thunderbird/policies/policies.json
#   - Thunderbird NM manifest   → /etc/thunderbird/native-messaging-hosts/os.claw.mail_ai.json
#   - Native host launcher      → /usr/lib/cos/claw-mail-ai-host
#   - Python host + deps        → /usr/lib/cos/mail-ai/, /usr/lib/cos/python/claw_os_sdk/
#
# Run as root. Re-run is idempotent (overwrites).
#
# After install, restart Thunderbird. The extension is force-installed
# via managed policy and loads on first launch of each profile.

set -euo pipefail

if [[ "${EUID}" -ne 0 ]]; then
  echo "must run as root" >&2
  exit 1
fi

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
EXT_SRC="${REPO_ROOT}/extensions/claw-mail-ai"
APP_SRC="${REPO_ROOT}/apps/mail-ai"
SDK_PY_SRC="${REPO_ROOT}/claw-os-sdk/python/src/claw_os_sdk"

EXT_ID="claw-mail-ai@claw.os"
EXT_DEST="/usr/share/claw/extensions/claw-mail-ai"
APP_DEST="/usr/lib/cos/mail-ai"
SDK_DEST="/usr/lib/cos/python/claw_os_sdk"
HOST_LAUNCHER="/usr/lib/cos/claw-mail-ai-host"
NM_MANIFEST="/etc/thunderbird/native-messaging-hosts/os.claw.mail_ai.json"
POLICY_FILE="/etc/thunderbird/policies/policies.json"
XPI_DEST_DIR="/usr/lib/thunderbird/distribution/extensions"
XPI_DEST="${XPI_DEST_DIR}/${EXT_ID}.xpi"

# Sanity checks.
for d in "${EXT_SRC}" "${APP_SRC}" "${SDK_PY_SRC}"; do
  if [[ ! -d "$d" ]]; then
    echo "error: source dir missing: $d" >&2
    exit 1
  fi
done
if ! command -v zip >/dev/null 2>&1; then
  echo "error: 'zip' is required to package the XPI. Install it (apt install zip)." >&2
  exit 1
fi

# ---------------------------------------------------------------------------
# 1. WebExtension source — kept around for sideloading/debugging.
# ---------------------------------------------------------------------------
echo "[claw-mail-ai] installing extension source → ${EXT_DEST}"
install -d -m 0755 "${EXT_DEST}"
cp -a "${EXT_SRC}/." "${EXT_DEST}/"
chmod -R a+rX "${EXT_DEST}"

# ---------------------------------------------------------------------------
# 2. Pack XPI for force-install via policies.json.
# ---------------------------------------------------------------------------
echo "[claw-mail-ai] packaging XPI       → ${XPI_DEST}"
install -d -m 0755 "${XPI_DEST_DIR}"
rm -f "${XPI_DEST}"
( cd "${EXT_DEST}" && zip -X -r -q "${XPI_DEST}" . \
    -x '*.git*' '*.DS_Store' 'test_*.py' '*.swp' '*.bak' )
chmod 0644 "${XPI_DEST}"

# ---------------------------------------------------------------------------
# 3. Python host + verb impls.
# ---------------------------------------------------------------------------
echo "[claw-mail-ai] installing Python host → ${APP_DEST}"
install -d -m 0755 "${APP_DEST}"
cp -a "${APP_SRC}/." "${APP_DEST}/"
rm -f "${APP_DEST}/test_main.py"     # don't ship tests
chmod 0755 "${APP_DEST}/native_host.py"

if [[ ! -d "${SDK_DEST}" ]]; then
  echo "[claw-mail-ai] installing claw-os-sdk → ${SDK_DEST}"
  install -d -m 0755 "${SDK_DEST}"
  cp -a "${SDK_PY_SRC}/." "${SDK_DEST}/"
fi

# ---------------------------------------------------------------------------
# 4. Native Messaging launcher + manifest.
# ---------------------------------------------------------------------------
echo "[claw-mail-ai] installing launcher    → ${HOST_LAUNCHER}"
install -d -m 0755 "$(dirname "${HOST_LAUNCHER}")"
cat > "${HOST_LAUNCHER}" <<EOF
#!/usr/bin/env bash
# Auto-generated by tools/install-mail-ai.sh — do not edit by hand.
set -eu
exec /usr/bin/python3 ${APP_DEST}/native_host.py "\$@"
EOF
chmod 0755 "${HOST_LAUNCHER}"

echo "[claw-mail-ai] installing NM manifest → ${NM_MANIFEST}"
install -d -m 0755 "$(dirname "${NM_MANIFEST}")"
cat > "${NM_MANIFEST}" <<EOF
{
  "name": "os.claw.mail_ai",
  "description": "Claw Mail AI — Native Messaging bridge between Thunderbird and apps/mail-ai",
  "path": "${HOST_LAUNCHER}",
  "type": "stdio",
  "allowed_extensions": ["${EXT_ID}"]
}
EOF
chmod 0644 "${NM_MANIFEST}"

# ---------------------------------------------------------------------------
# 5. Thunderbird policy — force-install the extension.
# ---------------------------------------------------------------------------
echo "[claw-mail-ai] installing policy      → ${POLICY_FILE}"
install -d -m 0755 "$(dirname "${POLICY_FILE}")"
cat > "${POLICY_FILE}" <<EOF
{
  "policies": {
    "ExtensionSettings": {
      "${EXT_ID}": {
        "installation_mode": "force_installed",
        "install_url": "file://${XPI_DEST}",
        "default_area": "navbar"
      }
    },
    "DisableTelemetry": true,
    "DisableAppUpdate": false,
    "BlockAboutConfig": false
  }
}
EOF
chmod 0644 "${POLICY_FILE}"

cat <<MSG

[claw-mail-ai] install complete.

Verify:
  1. Restart Thunderbird.
  2. Look for the Claw AI button on the toolbar and a "Mail Assistant"
     entry in the Spaces sidebar.
  3. Open a message — click the Claw AI button in the message header
     to see a Summary popup.
  4. Open Tools → Add-ons and Themes → check that "Claw Mail AI" is
     installed and enabled.
  5. To debug the Native Messaging bridge:
       journalctl --user -t thunderbird
       /usr/bin/python3 ${APP_DEST}/native_host.py --probe

If the extension doesn't appear, confirm:
  - ${XPI_DEST} exists and is readable
  - ${POLICY_FILE} is parseable JSON
  - The Thunderbird policy mechanism is honored (>=68): check
    Help → Troubleshooting Information → Important Modified Preferences

MSG
