#!/usr/bin/env bash
# tools/install-browser-agent.sh
#
# Install the Claw Agent WebExtension and its Native Messaging host system-wide.
#
#   - WebExtension source       → /usr/share/claw/extensions/claw-agent-browser/
#   - Chromium managed policy   → /etc/chromium/policies/managed/claw-agent.json
#   - Chromium NM host manifest → /etc/chromium/native-messaging-hosts/com.clawos.browser.json
#   - Native host launcher      → /usr/lib/cos/claw-browser-host
#
# Run as root.  Re-run is idempotent (overwrites).
#
# After install, restart Chromium.  The extension is force-installed via
# managed policy, so it loads automatically and is non-removable for the user.

set -euo pipefail

if [[ "${EUID}" -ne 0 ]]; then
  echo "must run as root" >&2
  exit 1
fi

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
EXT_SRC="${REPO_ROOT}/extensions/claw-agent-browser"
APP_SRC="${REPO_ROOT}/apps/browser-attached"

EXT_DEST="/usr/share/claw/extensions/claw-agent-browser"
HOST_LAUNCHER="/usr/lib/cos/claw-browser-host"
NM_MANIFEST="/etc/chromium/native-messaging-hosts/com.clawos.browser.json"
POLICY_FILE="/etc/chromium/policies/managed/claw-agent.json"

# Extension ID is deterministic when packed with a known key, but for the MVP
# we ship the unpacked extension and force-install it by absolute path on disk.
# Callers can override CLAW_EXT_ID once they generate a stable packed CRX.
EXT_ID="${CLAW_EXT_ID:-}"

echo "[claw] installing WebExtension source → ${EXT_DEST}"
install -d -m 0755 "${EXT_DEST}"
cp -a "${EXT_SRC}/." "${EXT_DEST}/"
chmod -R a+rX "${EXT_DEST}"

echo "[claw] installing native-host launcher → ${HOST_LAUNCHER}"
install -d -m 0755 "$(dirname "${HOST_LAUNCHER}")"
cat > "${HOST_LAUNCHER}" <<EOF
#!/usr/bin/env bash
# Auto-generated by install-browser-agent.sh — do not edit by hand.
exec /usr/bin/python3 "${APP_SRC}/native_host.py" "\$@"
EOF
chmod 0755 "${HOST_LAUNCHER}"

echo "[claw] installing Native Messaging manifest → ${NM_MANIFEST}"
install -d -m 0755 "$(dirname "${NM_MANIFEST}")"
if [[ -n "${EXT_ID}" ]]; then
  ALLOWED_ORIGINS=$(printf '"chrome-extension://%s/"' "${EXT_ID}")
else
  # No stable ID yet → leave allowed_origins empty.  After the first load the
  # admin/installer must edit this file with the extension's runtime ID
  # (chrome://extensions shows it), then restart Chromium.
  ALLOWED_ORIGINS=""
fi
cat > "${NM_MANIFEST}" <<EOF
{
  "name": "com.clawos.browser",
  "description": "Claw Agent — bridge between Chromium and the cos kernel",
  "path": "${HOST_LAUNCHER}",
  "type": "stdio",
  "allowed_origins": [${ALLOWED_ORIGINS}]
}
EOF
chmod 0644 "${NM_MANIFEST}"

echo "[claw] installing Chromium managed policy → ${POLICY_FILE}"
install -d -m 0755 "$(dirname "${POLICY_FILE}")"
cat > "${POLICY_FILE}" <<EOF
{
  "ExtensionInstallSources": ["file:///*"],
  "ExtensionSettings": {
    "*": { "installation_mode": "allowed" }
  },
  "ExtensionInstallAllowlist": ["*"]
}
EOF
chmod 0644 "${POLICY_FILE}"

cat <<MSG

[claw] install complete.

Next steps:
  1. Launch Chromium.
  2. chrome://extensions → Developer mode ON → Load unpacked → ${EXT_DEST}
  3. Note the assigned Extension ID (32 lowercase letters).
  4. Re-run this script with CLAW_EXT_ID=<id> to wire up Native Messaging:
       CLAW_EXT_ID=<id> sudo ${BASH_SOURCE[0]}
  5. Restart Chromium.

To verify the bridge:
  ls -l \$XDG_RUNTIME_DIR/claw-browser.sock     # socket should exist
  cos perms grant browser.tabs.read --wild      # one-time per session
  cos app browser-attached tabs.list            # should print your tabs

MSG
