#!/usr/bin/env bash
# tools/install-mail-ai.sh
#
# Install the Claw Mail AI WebExtension and its Native Messaging host
# system-wide for the locally installed Thunderbird.
#
#   - WebExtension source       → /usr/share/claw/extensions/claw-mail-ai/
#   - Thunderbird policies      → /etc/thunderbird/policies/policies.json
#   - Thunderbird NM manifest   → /etc/thunderbird/native-messaging-hosts/os.claw.mail_ai.json
#   - Native host launcher      → /usr/lib/cos/claw-mail-ai-host
#   - Python host + deps        → /usr/lib/cos/mail-ai/, /usr/lib/cos/python/claw_os_sdk/, /usr/lib/cos/python/cos_runtime/
#
# Run as root. Re-run is idempotent (overwrites).
#
# After install, restart Thunderbird. The extension is force-installed
# via managed policy and loads on first launch of each profile.

set -euo pipefail

if [[ "${EUID}" -ne 0 ]]; then
  echo "must run as root" >&2
  exit 1
fi

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
EXT_SRC="${REPO_ROOT}/extensions/claw-mail-ai"
APP_SRC="${REPO_ROOT}/apps/mail-ai"
SDK_PY_SRC="${REPO_ROOT}/claw-os-sdk/python/src/claw_os_sdk"
RUNTIME_PY_SRC="${REPO_ROOT}/cos-runtime/python/src/cos_runtime"

EXT_ID="claw-mail-ai@claw.os"
EXT_DEST="/usr/share/claw/extensions/claw-mail-ai"
APP_DEST="/usr/lib/cos/mail-ai"
SDK_DEST="/usr/lib/cos/python/claw_os_sdk"
RUNTIME_DEST="/usr/lib/cos/python/cos_runtime"
HOST_LAUNCHER="/usr/lib/cos/claw-mail-ai-host"
NM_MANIFEST="/etc/thunderbird/native-messaging-hosts/os.claw.mail_ai.json"
POLICY_FILE="/etc/thunderbird/policies/policies.json"
XPI_DEST_DIR="/usr/lib/thunderbird/distribution/extensions"
XPI_DEST="${XPI_DEST_DIR}/${EXT_ID}.xpi"

# Sanity checks.
for d in "${EXT_SRC}" "${APP_SRC}" "${SDK_PY_SRC}" "${RUNTIME_PY_SRC}"; do
  if [[ ! -d "$d" ]]; then
    echo "error: source dir missing: $d" >&2
    exit 1
  fi
done
if ! command -v zip >/dev/null 2>&1; then
  echo "error: 'zip' is required to package the XPI. Install it (apt install zip)." >&2
  exit 1
fi

# ---------------------------------------------------------------------------
# 1. WebExtension source — kept around for sideloading/debugging.
# ---------------------------------------------------------------------------
echo "[claw-mail-ai] installing extension source → ${EXT_DEST}"
install -d -m 0755 "${EXT_DEST}"
cp -a "${EXT_SRC}/." "${EXT_DEST}/"
chmod -R a+rX "${EXT_DEST}"

# ---------------------------------------------------------------------------
# 2. Pack XPI for force-install via policies.json.
# ---------------------------------------------------------------------------
echo "[claw-mail-ai] packaging XPI       → ${XPI_DEST}"
install -d -m 0755 "${XPI_DEST_DIR}"
rm -f "${XPI_DEST}"
( cd "${EXT_DEST}" && zip -X -r -q "${XPI_DEST}" . \
    -x '*.git*' '*.DS_Store' 'test_*.py' '*.swp' '*.bak' )
chmod 0644 "${XPI_DEST}"

# ---------------------------------------------------------------------------
# 3. Python host + verb impls.
# ---------------------------------------------------------------------------
echo "[claw-mail-ai] installing Python host → ${APP_DEST}"
install -d -m 0755 "${APP_DEST}"
cp -a "${APP_SRC}/." "${APP_DEST}/"
rm -f "${APP_DEST}/test_main.py"     # don't ship tests
chmod 0755 "${APP_DEST}/native_host.py"

# Always refresh the SDK/runtime trees so re-runs propagate fixes. The
# previous `[[ ! -d "${SDK_DEST}" ]]` guard meant the first install
# pinned a snapshot of the SDK forever and subsequent script runs
# silently shipped stale code.
echo "[claw-mail-ai] installing claw-os-sdk → ${SDK_DEST}"
install -d -m 0755 "${SDK_DEST}"
cp -af "${SDK_PY_SRC}/." "${SDK_DEST}/"
chmod -R a+rX "${SDK_DEST}"

echo "[claw-mail-ai] installing cos-runtime → ${RUNTIME_DEST}"
install -d -m 0755 "${RUNTIME_DEST}"
cp -af "${RUNTIME_PY_SRC}/." "${RUNTIME_DEST}/"
chmod -R a+rX "${RUNTIME_DEST}"

# ---------------------------------------------------------------------------
# 4. Native Messaging launcher + manifest.
# ---------------------------------------------------------------------------
echo "[claw-mail-ai] installing launcher    → ${HOST_LAUNCHER}"
install -d -m 0755 "$(dirname "${HOST_LAUNCHER}")"
cat > "${HOST_LAUNCHER}" <<EOF
#!/usr/bin/env bash
# Auto-generated by tools/install-mail-ai.sh — do not edit by hand.
set -eu
exec /usr/bin/python3 ${APP_DEST}/native_host.py "\$@"
EOF
chmod 0755 "${HOST_LAUNCHER}"

echo "[claw-mail-ai] installing NM manifest → ${NM_MANIFEST}"
install -d -m 0755 "$(dirname "${NM_MANIFEST}")"
cat > "${NM_MANIFEST}" <<EOF
{
  "name": "os.claw.mail_ai",
  "description": "Claw Mail AI — Native Messaging bridge between Thunderbird and apps/mail-ai",
  "path": "${HOST_LAUNCHER}",
  "type": "stdio",
  "allowed_extensions": ["${EXT_ID}"]
}
EOF
chmod 0644 "${NM_MANIFEST}"

# ---------------------------------------------------------------------------
# 5. Thunderbird policy — force-install the extension.
#
# We MERGE into any existing policies.json instead of clobbering it. The
# previous behavior overwrote site-admin or distro-supplied policy keys
# (DownloadDirectory, AppUpdateURL, …) every time the script ran. Now we
# read what's there, layer our keys on top, and write the union.
# ---------------------------------------------------------------------------
echo "[claw-mail-ai] installing policy      → ${POLICY_FILE}"
install -d -m 0755 "$(dirname "${POLICY_FILE}")"

OUR_POLICY=$(cat <<EOF
{
  "policies": {
    "ExtensionSettings": {
      "${EXT_ID}": {
        "installation_mode": "force_installed",
        "install_url": "file://${XPI_DEST}",
        "default_area": "navbar"
      }
    },
    "DisableTelemetry": true,
    "DisableAppUpdate": false,
    "BlockAboutConfig": false
  }
}
EOF
)

merge_policy() {
  local existing="$1"
  local ours="$2"
  if command -v jq >/dev/null 2>&1; then
    # Deep-merge: ours wins on collisions, but keys we don't touch
    # (e.g. existing site policies) are preserved.
    jq -s '.[0] * .[1]' <(printf '%s' "$existing") <(printf '%s' "$ours")
  else
    /usr/bin/env python3 - "$existing" "$ours" <<'PY'
import json, sys
def deep_merge(a, b):
    if isinstance(a, dict) and isinstance(b, dict):
        out = dict(a)
        for k, v in b.items():
            out[k] = deep_merge(a.get(k), v) if k in a else v
        return out
    return b
existing = json.loads(sys.argv[1]) if sys.argv[1].strip() else {}
ours = json.loads(sys.argv[2])
print(json.dumps(deep_merge(existing, ours), indent=2))
PY
  fi
}

EXISTING_POLICY="{}"
if [[ -f "${POLICY_FILE}" ]]; then
  # If the file is unparseable, back it up and start from {} — we never
  # want a broken policies.json to brick Thunderbird on the next launch.
  if /usr/bin/env python3 -c "import json,sys; json.load(open(sys.argv[1]))" "${POLICY_FILE}" 2>/dev/null; then
    EXISTING_POLICY="$(cat "${POLICY_FILE}")"
  else
    echo "warning: ${POLICY_FILE} is not valid JSON — backing up to ${POLICY_FILE}.bak" >&2
    cp -a "${POLICY_FILE}" "${POLICY_FILE}.bak"
  fi
fi

MERGED_POLICY="$(merge_policy "${EXISTING_POLICY}" "${OUR_POLICY}")"
printf '%s\n' "${MERGED_POLICY}" > "${POLICY_FILE}"
chmod 0644 "${POLICY_FILE}"

cat <<MSG

[claw-mail-ai] install complete.

Verify:
  1. Restart Thunderbird.
  2. Look for the Claw AI button on the toolbar and a "Mail Assistant"
     entry in the Spaces sidebar.
  3. Open a message — click the Claw AI button in the message header
     to see a Summary popup.
  4. Open Tools → Add-ons and Themes → check that "Claw Mail AI" is
     installed and enabled.
  5. To debug the Native Messaging bridge:
       journalctl --user -t thunderbird
       /usr/bin/python3 ${APP_DEST}/native_host.py --probe

If the extension doesn't appear, confirm:
  - ${XPI_DEST} exists and is readable
  - ${POLICY_FILE} is parseable JSON
  - The Thunderbird policy mechanism is honored (>=68): check
    Help → Troubleshooting Information → Important Modified Preferences

MSG
