use super::*;

fn user(content: &str, accept: bool) -> ConversationTurn {
    ConversationTurn {
        role: TurnRole::User,
        content: content.to_string(),
        tool_calls: vec![],
        user_acceptance: accept,
    }
}

fn assistant(content: &str, tools: Vec<&str>) -> ConversationTurn {
    ConversationTurn {
        role: TurnRole::Assistant,
        content: content.to_string(),
        tool_calls: tools.into_iter().map(String::from).collect(),
        user_acceptance: false,
    }
}

#[test]
fn slugify_basic() {
    assert_eq!(slugify("PDF Extract Tool!"), "pdf-extract-tool");
    assert_eq!(slugify("  ___  "), "skill");
    assert_eq!(slugify(""), "skill");
    assert_eq!(slugify("HelloWorld"), "helloworld");
}

#[test]
fn derive_title_caps_first_letter() {
    assert_eq!(derive_title("extract pdf metadata"), "Extract pdf metadata");
    assert_eq!(derive_title(""), "Untitled skill");
}

#[test]
fn derive_title_truncates_long() {
    let long =
        "extract metadata from a really long pdf with many fields and stuff that goes on";
    let t = derive_title(long);
    assert!(t.ends_with('…'));
    assert!(t.chars().count() <= 62);
}

#[test]
fn derive_description_first_sentence() {
    let s = derive_description("Extract metadata from PDFs.\nAlso compute checksums.");
    assert_eq!(s, "Extract metadata from PDFs.");
}

#[test]
fn derive_description_empty_fallback() {
    assert_eq!(derive_description("   "), "(generated by curator)");
}

#[test]
fn derive_description_handles_non_ascii() {
    // Regression: long non-ASCII inputs with no sentence terminator
    // used to byte-slice at index 200 and panic when the cut
    // landed mid-codepoint. The fixed implementation walks back to
    // the nearest char boundary instead.
    //
    // ① long CJK without terminators: each kanji is 3 bytes, so byte
    //    200 lands inside the 67th character. Must NOT panic.
    let cjk: String = "漢字".repeat(120); // 240 chars, 720 bytes
    let out = derive_description(&cjk);
    assert!(out.chars().all(|c| c == '漢' || c == '字'));
    assert!(out.len() <= 200);

    // ② emoji that straddles the 200-byte budget. "hi 🌍" * 60 ≈ 420
    //    bytes with a 4-byte emoji at boundary positions.
    let mixed: String = "hi 🌍 ".repeat(60);
    // Must not panic and must produce a non-empty string.
    let out = derive_description(&mixed);
    assert!(!out.is_empty());

    // ③ accented Latin that lands the cut mid-codepoint.
    let accented: String = "ñ".repeat(200); // 2 bytes per char → 400 bytes
    let out = derive_description(&accented);
    assert!(out.chars().all(|c| c == 'ñ'));
    // We asked for ≤200 bytes; with 'ñ' = 2 bytes that's ≤100 chars.
    assert!(out.chars().count() <= 100);

    // ④ explicit ASCII sentence terminator INSIDE multi-byte text
    //    still works (sanity check we didn't break the happy path).
    assert_eq!(derive_description("汉字.more text"), "汉字.");
}

#[test]
fn propose_rejects_too_few_assistant_turns() {
    let c = Curator::with_default_config();
    let turns = vec![user("do thing", true)];
    match c.propose(&turns) {
        CuratorOutcome::NotEnough { reason } => assert!(reason.contains("assistant turns")),
        other => panic!("expected NotEnough, got {other:?}"),
    }
}

#[test]
fn propose_rejects_no_tool_use() {
    let c = Curator::with_default_config();
    let turns = vec![
        user("do thing", false),
        assistant("ok", vec![]),
        assistant("done", vec![]),
        user("thanks", true),
    ];
    match c.propose(&turns) {
        CuratorOutcome::NotEnough { reason } => assert!(reason.contains("distinct tools")),
        other => panic!("expected NotEnough, got {other:?}"),
    }
}

#[test]
fn propose_rejects_without_user_acceptance() {
    let c = Curator::with_default_config();
    let turns = vec![
        user("extract metadata from pdf", false),
        assistant("ok", vec!["cos_fs"]),
        assistant("done", vec!["cos_fs"]),
    ];
    match c.propose(&turns) {
        CuratorOutcome::NotEnough { reason } => assert!(reason.contains("user-acceptance")),
        other => panic!("expected NotEnough, got {other:?}"),
    }
}

#[test]
fn propose_emits_draft_when_thresholds_met() {
    let c = Curator::with_default_config();
    let turns = vec![
        user("extract metadata from this pdf file", false),
        assistant("checking", vec!["cos_fs"]),
        assistant("here it is: ...", vec!["cos_fs"]),
        user("perfect, thanks", true),
    ];
    match c.propose(&turns) {
        CuratorOutcome::Drafted(d) => {
            assert_eq!(d.suggested_id, "extract-metadata-from-this-pdf-file");
            assert_eq!(d.title, "Extract metadata from this pdf file");
            assert!(d.description.starts_with("extract metadata"));
            assert_eq!(d.allowed_tools, vec!["cos_fs".to_string()]);
            assert_eq!(d.turns_used, 4);
            // 1 distinct tool + accepted -> Medium.
            assert_eq!(d.confidence, SkillConfidence::Medium);
        }
        other => panic!("expected Drafted, got {other:?}"),
    }
}

#[test]
fn high_confidence_requires_two_tools_and_four_assistants_and_acceptance() {
    let c = Curator::with_default_config();
    let turns = vec![
        user("research topic X", false),
        assistant("scan", vec!["cos_web"]),
        assistant("read", vec!["cos_fs"]),
        assistant("synth", vec!["cos_fs"]),
        assistant("write", vec!["cos_fs"]),
        user("perfect", true),
    ];
    match c.propose(&turns) {
        CuratorOutcome::Drafted(d) => assert_eq!(d.confidence, SkillConfidence::High),
        other => panic!("expected Drafted, got {other:?}"),
    }
}

#[test]
fn config_can_disable_acceptance_requirement() {
    let c = Curator::new(CuratorConfig {
        require_user_acceptance: false,
        ..CuratorConfig::default()
    });
    let turns = vec![
        user("extract", false),
        assistant("ok", vec!["cos_fs"]),
        assistant("done", vec!["cos_fs"]),
    ];
    assert!(matches!(c.propose(&turns), CuratorOutcome::Drafted(_)));
}

#[test]
fn max_turns_caps_inspection_window() {
    let c = Curator::new(CuratorConfig {
        max_turns: 3,
        min_assistant_turns: 1,
        min_distinct_tools: 1,
        require_user_acceptance: false,
    });
    // First user message in the full slice is "first" but max_turns=3
    // so curator only looks at the last 3 turns.
    let turns = vec![
        user("first earlier message", false),
        user("second earlier message", false),
        user("recent task message", false),
        assistant("ok", vec!["cos_fs"]),
        assistant("done", vec!["cos_fs"]),
    ];
    match c.propose(&turns) {
        CuratorOutcome::Drafted(d) => {
            assert_eq!(d.turns_used, 3);
            assert!(d.title.starts_with("Recent task"));
        }
        other => panic!("expected Drafted, got {other:?}"),
    }
}

#[test]
fn distinct_tools_dedupe_across_turns() {
    let c = Curator::with_default_config();
    let turns = vec![
        user("do work", false),
        assistant("a", vec!["cos_fs", "cos_fs"]),
        assistant("b", vec!["cos_fs"]),
        user("ok", true),
    ];
    if let CuratorOutcome::Drafted(d) = c.propose(&turns) {
        assert_eq!(d.allowed_tools.len(), 1);
    } else {
        panic!("expected Drafted");
    }
}

#[test]
fn extract_tool_calls_from_content_pulls_names() {
    let body = "[tool_use:cos_fs] {\"path\":\"/etc\"}\n[tool_use:cos_proc] {}";
    let names = extract_tool_calls_from_content(body);
    assert_eq!(names, vec!["cos_fs", "cos_proc"]);
}

#[test]
fn extract_tool_calls_ignores_lines_without_marker() {
    let body = "Plain assistant text\n[tool_result] something\n[tool_use:cos_log] {}";
    let names = extract_tool_calls_from_content(body);
    assert_eq!(names, vec!["cos_log"]);
}

#[test]
fn extract_tool_calls_skips_malformed_marker() {
    // Missing closing bracket -> no tool name.
    assert!(extract_tool_calls_from_content("[tool_use:never_closed").is_empty());
    // Empty name between colon and bracket -> skipped.
    assert!(extract_tool_calls_from_content("[tool_use:]").is_empty());
}

#[test]
fn message_to_turn_assistant_extracts_tool_calls() {
    let t = message_to_turn(
        "assistant",
        "[tool_use:cos_fs] {\"path\":\"/x\"}\n[tool_use:cos_proc] {}",
    )
    .unwrap();
    assert_eq!(t.role, TurnRole::Assistant);
    assert_eq!(t.tool_calls, vec!["cos_fs", "cos_proc"]);
    assert!(!t.user_acceptance);
}

#[test]
fn message_to_turn_hides_legacy_evidence_markers() {
    let turn = message_to_turn(
        "assistant",
        "Network is idle. [evidence:call_1 confidence=0.95]",
    )
    .unwrap();
    assert_eq!(turn.content, "Network is idle.");
}

#[test]
fn message_to_turn_user_does_not_scan_for_tool_use() {
    // Even if a user message contains the marker text, it should
    // be ignored — only assistants emit tool calls.
    let t = message_to_turn("user", "[tool_use:fake] {}").unwrap();
    assert_eq!(t.role, TurnRole::User);
    assert!(t.tool_calls.is_empty());
}

#[test]
fn message_to_turn_tool_role_carries_no_calls() {
    let t = message_to_turn("tool", "[tool_result] success").unwrap();
    assert_eq!(t.role, TurnRole::Tool);
    assert!(t.tool_calls.is_empty());
}

#[test]
fn message_to_turn_unknown_role_is_none() {
    assert!(message_to_turn("system", "hi").is_none());
    assert!(message_to_turn("frob", "hi").is_none());
}

#[test]
fn looks_like_acceptance_picks_up_phrases() {
    assert!(looks_like_acceptance("thanks!"));
    assert!(looks_like_acceptance("Perfect."));
    assert!(looks_like_acceptance("That worked, exactly what I needed"));
    assert!(looks_like_acceptance("Works perfectly"));
}

#[test]
fn looks_like_acceptance_avoids_false_positives() {
    assert!(!looks_like_acceptance("I think it's broken"));
    assert!(!looks_like_acceptance("perfectly broken"));
    assert!(!looks_like_acceptance(""));
    // Word "thanks" embedded in another phrase shouldn't trigger
    // the standalone-word path.
    assert!(!looks_like_acceptance("thanksgiving plans"));
}
