#!/usr/bin/env python3
"""Codegen for claw-os-sdk wire/v1 schemas.

Reads every ``wire/v1/*.schema.json`` and emits typed bindings into each
language tree:

    rust/src/generated.rs            serde-friendly structs
    python/src/claw_os_sdk/generated.py    TypedDict definitions
    node/src/generated.ts            TypeScript interfaces
    go/generated.go                  Go structs

This is intentionally a small, hand-rolled emitter — no external generator
dependency. It handles the subset of JSON Schema used by wire/v1:

  - object with `properties` (+ `required`, `additionalProperties`)
  - primitive types: string, integer, number, boolean
    (`integer` follows JSON Schema mathematical semantics, so finite
    `1`, `1.0`, and `1e0` values are equivalent; bounds run afterward)
  - arrays (with `items`)
  - `enum` ⇒ becomes a string with a doc-listed allow-list (kept loose to
    stay forward-compatible with kernel additions). For Rust/Python/Go we
    additionally emit a runtime validator so a server emitting an
    out-of-spec value can be detected, not silently accepted.
  - `const` (used for the wire_version field)
  - $defs / $ref for in-file definitions
  - oneOf (rendered as JsonValue / Any / unknown / any)

Run from the SDK root:

    python3 wire/codegen.py
"""

from __future__ import annotations

import argparse
import json
import pathlib
import sys
import textwrap

ROOT = pathlib.Path(__file__).resolve().parent.parent
WIRE_DIR = ROOT / "wire" / "v1"
CONTRACT_PATH = WIRE_DIR / "contract.json"
RUST_OUT = ROOT / "rust" / "src" / "generated.rs"
PY_OUT   = ROOT / "python" / "src" / "claw_os_sdk" / "generated.py"
TS_OUT   = ROOT / "node" / "src" / "generated.ts"
GO_OUT   = ROOT / "go" / "generated.go"
CORE_MCP_OUT = ROOT.parent / "core" / "src" / "agent" / "tools" / "mcp" / "generated.rs"
CRATE_MCP_OUT = ROOT.parent / "crates" / "cos-mcp-serve" / "src" / "generated.rs"

BANNER_LINES = [
    "DO NOT EDIT BY HAND.",
    "Generated by claw-os-sdk/wire/codegen.py from wire/v1/*.schema.json.",
    "Run `python3 wire/codegen.py` from the SDK root to regenerate.",
]


# --- helpers -----------------------------------------------------------

def _camel(name: str) -> str:
    if "_" not in name and "-" not in name and name[:1].isupper():
        return name
    parts = name.replace("-", "_").split("_")
    return "".join(p.capitalize() for p in parts if p)


def _snake(name: str) -> str:
    out = []
    for i, ch in enumerate(name):
        if ch.isupper() and i and not name[i - 1].isupper():
            out.append("_")
        out.append(ch.lower())
    return "".join(out).replace("-", "_")


def _is_scalar_schema(schema: dict) -> bool:
    """Return True when the schema describes a scalar (string / number /
    integer / boolean). Used by the Go emitter to decide whether
    ``omitempty`` will actually do anything for an optional field.
    Go's ``omitempty`` is a no-op on non-pointer struct values: a
    zero-valued struct still serialises as ``{}``, which silently
    diverges from what the other SDKs emit. For non-scalar optional
    fields we emit a pointer type instead.
    """
    if "$ref" in schema:
        return False
    if "oneOf" in schema or "anyOf" in schema:
        # Rendered as `interface{}` which is already a reference type.
        return True
    if "const" in schema:
        return True
    t = schema.get("type")
    if isinstance(t, list):
        return True
    if t in ("string", "integer", "number", "boolean"):
        return True
    # Arrays in Go are slices (already nil-zero), and maps likewise —
    # `omitempty` works for them. Only inline object structs ("type":
    # "object" with properties) need a pointer wrapper.
    if t == "array":
        return True
    if t == "object" and "properties" not in schema:
        return True
    return False


def load_schemas() -> list[tuple[str, dict]]:
    schemas: list[tuple[str, dict]] = []
    for path in sorted(WIRE_DIR.glob("*.schema.json")):
        name = path.stem.replace(".schema", "")
        with path.open() as fh:
            schemas.append((name, json.load(fh)))
    return schemas


def load_contract() -> dict:
    with CONTRACT_PATH.open(encoding="utf-8") as fh:
        return json.load(fh)


def _schema_json(schema: dict) -> str:
    return json.dumps(schema, sort_keys=True, separators=(",", ":"))


def _validation_schemas(
    schemas: list[tuple[str, dict]], contract: dict
) -> list[tuple[str, dict]]:
    by_name = dict(schemas)
    names = contract["validation"]["schemas"]
    missing = [name for name in names if name not in by_name]
    if missing:
        raise ValueError(f"validation schema not found: {', '.join(missing)}")
    return [(name, by_name[name]) for name in names]


def _validation_targets(
    schemas: list[tuple[str, dict]], contract: dict
) -> list[tuple[str, dict]]:
    targets = _validation_schemas(schemas, contract)
    by_name = dict(schemas)
    for target in contract["validation"].get("targets", []):
        rule = by_name[target["schema"]]
        for component in target["path"]:
            rule = rule[component]
        targets.append((target["name"], rule))
    return targets


# --- rust --------------------------------------------------------------

def rust_type(schema: dict, defs: dict, ctx: str) -> str:
    if "x-rust-type" in schema:
        return schema["x-rust-type"]
    if "$ref" in schema:
        ref = schema["$ref"].split("/")[-1]
        return _camel(ref)
    if "oneOf" in schema or "anyOf" in schema:
        return "serde_json::Value"
    if "const" in schema:
        v = schema["const"]
        if isinstance(v, bool):
            return "bool"
        if isinstance(v, int):
            # Default to i64 — narrowing to u8 silently corrupts any
            # future const integer > 255 (a build number, an HTTP
            # status, etc.). Only emit the smaller type when the schema
            # explicitly constrains the value into a u8 range.
            mn = schema.get("minimum")
            mx = schema.get("maximum")
            if mn is not None and mx is not None and 0 <= mn and mx <= 255:
                return "u8"
            if mn is not None and mn >= 0:
                return "u64"
            return "i64"
        return "String"
    t = schema.get("type")
    if isinstance(t, list):
        return "serde_json::Value"
    if t == "string":
        return "String"
    if t == "integer":
        # No const, no bounds → i64 is the universally-safe default for
        # wire integers. Schemas that need a smaller type can declare
        # `minimum`/`maximum` and we'll narrow accordingly.
        mn = schema.get("minimum")
        mx = schema.get("maximum")
        if mn is not None and mx is not None and 0 <= mn and mx <= 255:
            return "u8"
        if mn is not None and mn >= 0:
            return "u64"
        return "i64"
    if t == "number":
        return "f64"
    if t == "boolean":
        return "bool"
    if t == "array":
        inner = rust_type(schema.get("items", {}), defs, ctx)
        return f"Vec<{inner}>"
    if t == "object":
        if "properties" in schema:
            return _camel(ctx)
        return "serde_json::Value"
    return "serde_json::Value"


def rust_struct(name: str, schema: dict, defs: dict, out: list[str]) -> None:
    props = schema.get("properties", {})
    required = set(schema.get("required", []))
    title = schema.get("title", name)
    description = schema.get("description", "")
    doc = []
    if title:
        doc.append(f"/// {title}")
    for line in textwrap.wrap(description, 78):
        doc.append(f"/// {line}")
    if doc:
        out.extend(doc)
    out.append("#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]")
    out.append(f"pub struct {_camel(name)} {{")
    for pname, pschema in props.items():
        rust_ty = rust_type(pschema, defs, f"{name}_{pname}")
        rename = ""
        snake = _snake(pname)
        if snake != pname:
            rename = f'    #[serde(rename = "{pname}")]\n'
        if pname not in required:
            out.append(f'    #[serde(default, skip_serializing_if = "Option::is_none")]')
            out.append(f"{rename}    pub {snake}: Option<{rust_ty}>,")
        else:
            if rename:
                out.append(rename.rstrip())
            out.append(f"    pub {snake}: {rust_ty},")
    out.append("}")
    out.append("")


def emit_rust(schemas: list[tuple[str, dict]], contract: dict) -> str:
    body: list[str] = []
    body.append("// " + BANNER_LINES[0])
    for line in BANNER_LINES[1:]:
        body.append("// " + line)
    body.append("")
    body.append("#![allow(clippy::all)]")
    body.append("#![allow(non_snake_case, non_camel_case_types)]")
    body.append("")
    body.append("use serde_json;")
    body.append("")
    body.append(f"/// Expected wire-version value emitted by the kernel. The")
    body.append(f"/// generated [`Envelope`] type's runtime check accepts only")
    body.append(f"/// this constant; anything else is surfaced as an error.")
    expected_wire_version = contract["wire_version"]
    body.append(f"pub const EXPECTED_WIRE_VERSION: i64 = {expected_wire_version};")
    body.append("")
    body.append("/// Verify a deserialised envelope advertises a wire version this")
    body.append("/// SDK understands. Returns `Err(msg)` on mismatch.")
    body.append("///")
    body.append("/// Callers (typically `claw_os_sdk::envelope::Envelope::accept`)")
    body.append("/// should refuse to interpret the payload further when this")
    body.append("/// returns Err — a future kernel speaking wire/v2 must be")
    body.append("/// matched by an SDK that knows that protocol.")
    body.append("pub fn check_wire_version(seen: i64) -> Result<(), String> {")
    body.append("    if seen == EXPECTED_WIRE_VERSION {")
    body.append("        Ok(())")
    body.append("    } else {")
    body.append("        Err(format!(")
    body.append("            \"unsupported wire_version: got {}, expected {}\",")
    body.append("            seen, EXPECTED_WIRE_VERSION,")
    body.append("        ))")
    body.append("    }")
    body.append("}")
    body.append("")
    enum_validators: list[tuple[str, str, list]] = []
    for name, schema in schemas:
        rust_struct(name, schema, schema.get("$defs", {}), body)
        nested: list[tuple[str, dict]] = []
        _collect_nested(name, schema, nested)
        for nname, nschema in nested:
            rust_struct(nname, nschema, schema.get("$defs", {}), body)
        for def_name, def_schema in schema.get("$defs", {}).items():
            rust_struct(def_name, def_schema, {}, body)
        _collect_enum_validators(name, schema, enum_validators)
        for nname, nschema in nested:
            _collect_enum_validators(nname, nschema, enum_validators)
    for parent, field_name, values in enum_validators:
        fn = f"validate_{_snake(parent)}_{_snake(field_name)}"
        body.append(f"/// Reject values outside the {parent}.{field_name} enum.")
        body.append("///")
        body.append("/// The wire schema lists a closed set of allowed values; a kernel")
        body.append("/// that emits an unknown one should not be silently accepted.")
        body.append(f"pub fn {fn}(value: &str) -> Result<(), String> {{")
        rendered = ", ".join(f'"{v}"' for v in values)
        body.append(f"    const ALLOWED: &[&str] = &[{rendered}];")
        body.append("    if ALLOWED.iter().any(|a| *a == value) {")
        body.append("        Ok(())")
        body.append("    } else {")
        body.append(f"        Err(format!(\"invalid {parent}.{field_name} value: {{value}}\"))")
        body.append("    }")
        body.append("}")
        body.append("")
    _emit_rust_validation(body, _validation_targets(schemas, contract), contract)
    return "\n".join(body) + "\n"


def _collect_nested(name: str, schema: dict, acc: list[tuple[str, dict]]) -> None:
    """Walk properties / items and collect anonymous nested objects.

    Each entry produced has a fully-qualified ctx name (e.g. ``ai_usage``)
    matching what ``*_type`` helpers compute, so emitters can generate
    matching standalone struct / interface definitions for them.
    """
    props = schema.get("properties", {})
    for pname, pschema in props.items():
        ctx = f"{name}_{pname}"
        if pschema.get("type") == "object" and "properties" in pschema:
            acc.append((ctx, pschema))
            _collect_nested(ctx, pschema, acc)
        elif pschema.get("type") == "array":
            items = pschema.get("items", {})
            if items.get("type") == "object" and "properties" in items:
                acc.append((ctx, items))
                _collect_nested(ctx, items, acc)


def _collect_enum_validators(parent: str, schema: dict, acc: list) -> None:
    """Collect (parent, field, values) tuples for every string `enum`
    property — used to emit per-language runtime validators."""
    props = schema.get("properties", {})
    for pname, pschema in props.items():
        if pschema.get("type") == "string" and "enum" in pschema:
            acc.append((parent, pname, list(pschema["enum"])))


def _emit_rust_validation(
    body: list[str], schemas: list[tuple[str, dict]], contract: dict
) -> None:
    codes = contract["validation"]["error_codes"]
    body.extend([
        "/// Stable failure returned by generated wire validators.",
        "#[derive(Debug, Clone, PartialEq, Eq)]",
        "pub struct WireDecodeError {",
        "    pub code: &'static str,",
        "    pub schema: &'static str,",
        "    pub path: String,",
        "    pub reason: String,",
        "}",
        "",
        "impl std::fmt::Display for WireDecodeError {",
        "    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {",
        "        write!(f, \"{}: invalid {} at {}: {}\", self.code, self.schema, self.path, self.reason)",
        "    }",
        "}",
        "",
        "impl std::error::Error for WireDecodeError {}",
        "",
    ])
    for key, value in codes.items():
        body.append(f'pub const WIRE_{key.upper()}: &str = "{value}";')
    body.extend([
        "",
        "fn wire_error(",
        "    code: &'static str,",
        "    schema: &'static str,",
        "    path: &str,",
        "    reason: impl Into<String>,",
        ") -> WireDecodeError {",
        "    WireDecodeError { code, schema, path: path.to_string(), reason: reason.into() }",
        "}",
        "",
        "fn validate_wire_schema(",
        "    rule: &serde_json::Value,",
        "    root: &serde_json::Value,",
        "    value: &serde_json::Value,",
        "    schema_name: &'static str,",
        "    path: &str,",
        ") -> Result<(), WireDecodeError> {",
        '    if let Some(reference) = rule.get("$ref").and_then(serde_json::Value::as_str) {',
        "        let name = reference.rsplit('/').next().unwrap_or_default();",
        '        let target = root.get("$defs").and_then(|defs| defs.get(name)).ok_or_else(|| {',
        '            wire_error(WIRE_TYPE, schema_name, path, format!("unresolved schema reference {reference}"))',
        "        })?;",
        "        return validate_wire_schema(target, root, value, schema_name, path);",
        "    }",
        '    if let Some(branches) = rule.get("oneOf").and_then(serde_json::Value::as_array) {',
        "        let matches = branches.iter().filter(|branch| {",
        "            validate_wire_schema(branch, root, value, schema_name, path).is_ok()",
        "        }).count();",
        "        if matches != 1 {",
        '            return Err(wire_error(WIRE_ONE_OF, schema_name, path, "expected exactly one allowed shape"));',
        "        }",
        "        return Ok(());",
        "    }",
        '    if let Some(expected) = rule.get("type").and_then(serde_json::Value::as_str) {',
        "        let valid = match expected {",
        '            "object" => value.is_object(),',
        '            "array" => value.is_array(),',
        '            "string" => value.is_string(),',
        '            "integer" => value.as_i64().is_some() || value.as_u64().is_some() || value.as_f64().is_some_and(|number| number.is_finite() && number.fract() == 0.0),',
        '            "number" => value.is_number(),',
        '            "boolean" => value.is_boolean(),',
        '            "null" => value.is_null(),',
        "            _ => false,",
        "        };",
        "        if !valid {",
        '            return Err(wire_error(WIRE_TYPE, schema_name, path, format!("expected {expected}")));',
        "        }",
        "    }",
        '    if let Some(expected) = rule.get("const") {',
        "        if value != expected {",
        '            return Err(wire_error(WIRE_CONST, schema_name, path, "value does not match const"));',
        "        }",
        "    }",
        '    if let Some(allowed) = rule.get("enum").and_then(serde_json::Value::as_array) {',
        "        if !allowed.contains(value) {",
        '            return Err(wire_error(WIRE_ENUM, schema_name, path, "value is not in the allowed enum"));',
        "        }",
        "    }",
        "    if let Some(number) = value.as_f64() {",
        '        if let Some(minimum) = rule.get("minimum").and_then(serde_json::Value::as_f64) {',
        "            if number < minimum {",
        '                return Err(wire_error(WIRE_MINIMUM, schema_name, path, format!("must be >= {minimum}")));',
        "            }",
        "        }",
        '        if let Some(maximum) = rule.get("maximum").and_then(serde_json::Value::as_f64) {',
        "            if number > maximum {",
        '                return Err(wire_error(WIRE_MAXIMUM, schema_name, path, format!("must be <= {maximum}")));',
        "            }",
        "        }",
        "    }",
        "    if let Some(object) = value.as_object() {",
        '        if let Some(required) = rule.get("required").and_then(serde_json::Value::as_array) {',
        "            for field in required {",
        "                let field = field.as_str().unwrap_or_default();",
        "                if !object.contains_key(field) {",
        "                    let field_path = format!(\"{path}.{field}\");",
        '                    return Err(wire_error(WIRE_REQUIRED, schema_name, &field_path, "field is required"));',
        "                }",
        "            }",
        "        }",
        '        if let Some(properties) = rule.get("properties").and_then(serde_json::Value::as_object) {',
        "            let mut names: Vec<&String> = properties.keys().collect();",
        "            names.sort();",
        "            for name in names {",
        "                if let Some(field_value) = object.get(name) {",
        "                    let field_path = format!(\"{path}.{name}\");",
        "                    validate_wire_schema(&properties[name], root, field_value, schema_name, &field_path)?;",
        "                }",
        "            }",
        "            let mut extras: Vec<&String> = object.keys().filter(|name| !properties.contains_key(*name)).collect();",
        "            extras.sort();",
        '            if rule.get("additionalProperties") == Some(&serde_json::Value::Bool(false)) {',
        "                if let Some(name) = extras.first() {",
        "                    let field_path = format!(\"{path}.{name}\");",
        '                    return Err(wire_error(WIRE_UNKNOWN_FIELD, schema_name, &field_path, "unknown field"));',
        "                }",
        '            } else if let Some(additional) = rule.get("additionalProperties").filter(|v| v.is_object()) {',
        "                for name in extras {",
        "                    let field_path = format!(\"{path}.{name}\");",
        "                    validate_wire_schema(additional, root, &object[name], schema_name, &field_path)?;",
        "                }",
        "            }",
        "        }",
        "    }",
        "    if let Some(items) = value.as_array() {",
        '        if let Some(item_rule) = rule.get("items") {',
        "            for (index, item) in items.iter().enumerate() {",
        "                let item_path = format!(\"{path}[{index}]\");",
        "                validate_wire_schema(item_rule, root, item, schema_name, &item_path)?;",
        "            }",
        "        }",
        "    }",
        "    Ok(())",
        "}",
        "",
        "fn normalize_wire_integers(",
        "    rule: &serde_json::Value,",
        "    root: &serde_json::Value,",
        "    value: &mut serde_json::Value,",
        ") {",
        '    if let Some(reference) = rule.get("$ref").and_then(serde_json::Value::as_str) {',
        "        let name = reference.rsplit('/').next().unwrap_or_default();",
        '        if let Some(target) = root.get("$defs").and_then(|defs| defs.get(name)) {',
        "            normalize_wire_integers(target, root, value);",
        "        }",
        "        return;",
        "    }",
        '    if let Some(branches) = rule.get("oneOf").and_then(serde_json::Value::as_array) {',
        "        if let Some(branch) = branches.iter().find(|branch| {",
        '            validate_wire_schema(branch, root, value, "generated", "$").is_ok()',
        "        }) {",
        "            normalize_wire_integers(branch, root, value);",
        "        }",
        "        return;",
        "    }",
        '    if rule.get("type").and_then(serde_json::Value::as_str) == Some("integer")',
        "        && value.as_i64().is_none()",
        "        && value.as_u64().is_none()",
        "    {",
        "        if let Some(number) = value.as_f64() {",
        "            if number >= 0.0 && number <= u64::MAX as f64 {",
        "                *value = serde_json::Value::Number(serde_json::Number::from(number as u64));",
        "            } else if number >= i64::MIN as f64 && number <= i64::MAX as f64 {",
        "                *value = serde_json::Value::Number(serde_json::Number::from(number as i64));",
        "            }",
        "        }",
        "        return;",
        "    }",
        "    if let Some(object) = value.as_object_mut() {",
        '        if let Some(properties) = rule.get("properties").and_then(serde_json::Value::as_object) {',
        "            for (name, field_rule) in properties {",
        "                if let Some(field_value) = object.get_mut(name) {",
        "                    normalize_wire_integers(field_rule, root, field_value);",
        "                }",
        "            }",
        '            if let Some(additional) = rule.get("additionalProperties").filter(|v| v.is_object()) {',
        "                for (name, field_value) in object {",
        "                    if !properties.contains_key(name) {",
        "                        normalize_wire_integers(additional, root, field_value);",
        "                    }",
        "                }",
        "            }",
        "        }",
        "    } else if let Some(items) = value.as_array_mut() {",
        '        if let Some(item_rule) = rule.get("items") {',
        "            for item in items {",
        "                normalize_wire_integers(item_rule, root, item);",
        "            }",
        "        }",
        "    }",
        "}",
        "",
    ])
    for name, schema in schemas:
        const_name = f"_WIRE_SCHEMA_{name.upper()}"
        fn_name = f"validate_{_snake(name)}"
        body.append(f'const {const_name}: &str = r###"{_schema_json(schema)}"###;')
        body.append(f"pub fn {fn_name}(value: &serde_json::Value) -> Result<(), WireDecodeError> {{")
        body.append(f"    let schema: serde_json::Value = serde_json::from_str({const_name})")
        body.append('        .expect("generated wire schema must be valid JSON");')
        body.append(f'    validate_wire_schema(&schema, &schema, value, "{_camel(name)}", "$")')
        body.append("}")
        body.append("")
        body.append(
            f"pub fn normalize_{_snake(name)}_integers(value: &mut serde_json::Value) {{"
        )
        body.append(f"    let schema: serde_json::Value = serde_json::from_str({const_name})")
        body.append('        .expect("generated wire schema must be valid JSON");')
        body.append("    normalize_wire_integers(&schema, &schema, value);")
        body.append("}")
        body.append("")


# --- python ------------------------------------------------------------

def py_type(schema: dict, defs: dict, ctx: str) -> str:
    if "$ref" in schema:
        ref = schema["$ref"].split("/")[-1]
        return f'"{_camel(ref)}"'
    if "oneOf" in schema or "anyOf" in schema:
        return "Any"
    if "const" in schema:
        v = schema["const"]
        if isinstance(v, bool):
            return "bool"
        if isinstance(v, int):
            return "int"
        return "str"
    t = schema.get("type")
    if isinstance(t, list):
        return "Any"
    if t == "string":
        return "str"
    if t == "integer":
        return "int"
    if t == "number":
        return "float"
    if t == "boolean":
        return "bool"
    if t == "array":
        inner = py_type(schema.get("items", {}), defs, ctx)
        return f"List[{inner}]"
    if t == "object":
        if "properties" in schema:
            return f'"{_camel(ctx)}"'
        return "Dict[str, Any]"
    return "Any"


def py_typed_dict(name: str, schema: dict, defs: dict, out: list[str]) -> None:
    props = schema.get("properties", {})
    required = set(schema.get("required", []))
    title = schema.get("title", name)
    description = schema.get("description", "")
    public_name = _camel(name)
    required_props = [(pname, pschema) for pname, pschema in props.items() if pname in required]
    optional_props = [(pname, pschema) for pname, pschema in props.items() if pname not in required]
    out.append("")
    if required_props and optional_props:
        base_name = f"_{public_name}Required"
        out.append(f"class {base_name}(TypedDict):")
        for pname, pschema in required_props:
            ty = py_type(pschema, defs, f"{name}_{pname}")
            out.append(f"    {pname}: {ty}")
        out.append("")
        out.append(f"class {public_name}({base_name}, total=False):")
        fields = optional_props
    elif required_props:
        out.append(f"class {public_name}(TypedDict):")
        fields = required_props
    else:
        out.append(f"class {public_name}(TypedDict, total=False):")
        fields = optional_props
    out.append(f'    """{title}.')
    if description:
        out.append("")
        for line in textwrap.wrap(description, 76):
            out.append(f"    {line}")
    out.append('    """')
    if not fields:
        out.append("    pass")
        return
    for pname, pschema in fields:
        ty = py_type(pschema, defs, f"{name}_{pname}")
        out.append(f"    {pname}: {ty}")


def emit_python(schemas: list[tuple[str, dict]], contract: dict) -> str:
    body: list[str] = []
    body.append('"""' + BANNER_LINES[0])
    for line in BANNER_LINES[1:]:
        body.append(line)
    body.append('"""')
    body.append("")
    body.append("from __future__ import annotations")
    body.append("")
    body.append("import json")
    body.append("import math")
    body.append("")
    body.append("from typing import Any, Dict, List, Mapping, TypedDict")
    body.append("")
    body.append(f"# Wire-version value the kernel must advertise. See")
    body.append(f"# wire/v1/envelope.schema.json.")
    body.append(f"EXPECTED_WIRE_VERSION = {contract['wire_version']}")
    for key, value in contract["json_rpc_error_codes"].items():
        body.append(f"JSONRPC_ERROR_{key.upper()} = {value}")
    body.append("")
    body.append("")
    body.append("def check_wire_version(envelope: Mapping[str, object]) -> None:")
    body.append('    """Raise :class:`ValueError` if the envelope advertises a wire')
    body.append('    version this SDK does not understand. Returns ``None`` on')
    body.append('    success; callers that prefer non-raising semantics can wrap')
    body.append('    this in ``try``.')
    body.append("")
    body.append("    Mirrors the Rust ``generated::check_wire_version`` helper so")
    body.append("    a future wire/v2 kernel never gets silently downgraded by a")
    body.append("    wire/v1 SDK.")
    body.append('    """')
    body.append('    seen = envelope.get("wire_version")')
    body.append("    if seen != EXPECTED_WIRE_VERSION:")
    body.append("        raise ValueError(")
    body.append("            f\"unsupported wire_version: got {seen!r}, expected {EXPECTED_WIRE_VERSION}\"")
    body.append("        )")
    body.append("")
    enum_validators: list[tuple[str, str, list]] = []
    for name, schema in schemas:
        py_typed_dict(name, schema, schema.get("$defs", {}), body)
        nested: list[tuple[str, dict]] = []
        _collect_nested(name, schema, nested)
        for nname, nschema in nested:
            py_typed_dict(nname, nschema, schema.get("$defs", {}), body)
        for def_name, def_schema in schema.get("$defs", {}).items():
            py_typed_dict(def_name, def_schema, {}, body)
        _collect_enum_validators(name, schema, enum_validators)
        for nname, nschema in nested:
            _collect_enum_validators(nname, nschema, enum_validators)
    for parent, field_name, values in enum_validators:
        fn = f"validate_{_snake(parent)}_{_snake(field_name)}"
        body.append("")
        body.append(f"def {fn}(value: str) -> None:")
        body.append(f"    \"\"\"Raise ValueError if value is not in the {parent}.{field_name}")
        body.append(f"    enum. Mirrors generated::{fn}.\"\"\"")
        body.append(f"    allowed = {values!r}")
        body.append("    if value not in allowed:")
        body.append(f"        raise ValueError(f\"invalid {parent}.{field_name} value: {{value!r}}\")")
    _emit_python_validation(body, _validation_targets(schemas, contract), contract)
    body.append("")
    return "\n".join(body) + "\n"


def _emit_python_validation(
    body: list[str], schemas: list[tuple[str, dict]], contract: dict
) -> None:
    codes = contract["validation"]["error_codes"]
    body.extend([
        "",
        "class WireDecodeError(ValueError):",
        '    """Stable failure returned by generated wire validators."""',
        "",
        "    def __init__(self, code: str, schema: str, path: str, reason: str) -> None:",
        "        self.code = code",
        "        self.schema = schema",
        "        self.path = path",
        "        self.reason = reason",
        '        super().__init__(f"{code}: invalid {schema} at {path}: {reason}")',
        "",
    ])
    for key, value in codes.items():
        body.append(f'WIRE_{key.upper()} = "{value}"')
    body.extend([
        "",
        "def _wire_error(code: str, schema: str, path: str, reason: str) -> WireDecodeError:",
        "    return WireDecodeError(code, schema, path, reason)",
        "",
        "def _validate_wire_schema(",
        "    rule: Mapping[str, Any],",
        "    root: Mapping[str, Any],",
        "    value: Any,",
        "    schema_name: str,",
        "    path: str,",
        ") -> None:",
        '    reference = rule.get("$ref")',
        "    if isinstance(reference, str):",
        '        target = root.get("$defs", {}).get(reference.rsplit("/", 1)[-1])',
        "        if not isinstance(target, Mapping):",
        '            raise _wire_error(WIRE_TYPE, schema_name, path, f"unresolved schema reference {reference}")',
        "        _validate_wire_schema(target, root, value, schema_name, path)",
        "        return",
        '    branches = rule.get("oneOf")',
        "    if isinstance(branches, list):",
        "        matches = 0",
        "        for branch in branches:",
        "            try:",
        "                _validate_wire_schema(branch, root, value, schema_name, path)",
        "            except WireDecodeError:",
        "                continue",
        "            matches += 1",
        "        if matches != 1:",
        '            raise _wire_error(WIRE_ONE_OF, schema_name, path, "expected exactly one allowed shape")',
        "        return",
        '    expected = rule.get("type")',
        "    valid = {",
        '        "object": isinstance(value, Mapping),',
        '        "array": isinstance(value, list),',
        '        "string": isinstance(value, str),',
        '        "integer": (isinstance(value, int) and not isinstance(value, bool)) or (isinstance(value, float) and math.isfinite(value) and value.is_integer()),',
        '        "number": isinstance(value, (int, float)) and not isinstance(value, bool) and math.isfinite(value),',
        '        "boolean": isinstance(value, bool),',
        '        "null": value is None,',
        "    }",
        "    if isinstance(expected, str) and not valid.get(expected, False):",
        '        raise _wire_error(WIRE_TYPE, schema_name, path, f"expected {expected}")',
        '    if "const" in rule and value != rule["const"]:',
        '        raise _wire_error(WIRE_CONST, schema_name, path, "value does not match const")',
        '    allowed = rule.get("enum")',
        "    if isinstance(allowed, list) and value not in allowed:",
        '        raise _wire_error(WIRE_ENUM, schema_name, path, "value is not in the allowed enum")',
        "    if isinstance(value, (int, float)) and not isinstance(value, bool):",
        '        minimum = rule.get("minimum")',
        "        if minimum is not None and value < minimum:",
        '            raise _wire_error(WIRE_MINIMUM, schema_name, path, f"must be >= {minimum}")',
        '        maximum = rule.get("maximum")',
        "        if maximum is not None and value > maximum:",
        '            raise _wire_error(WIRE_MAXIMUM, schema_name, path, f"must be <= {maximum}")',
        "    if isinstance(value, Mapping):",
        '        required = rule.get("required", [])',
        "        for field in required:",
        "            if field not in value:",
        '                raise _wire_error(WIRE_REQUIRED, schema_name, f"{path}.{field}", "field is required")',
        '        properties = rule.get("properties")',
        "        if isinstance(properties, Mapping):",
        "            for field in sorted(properties):",
        "                if field in value:",
        "                    _validate_wire_schema(",
        "                        properties[field], root, value[field], schema_name, f\"{path}.{field}\"",
        "                    )",
        "            extras = sorted(field for field in value if field not in properties)",
        '            additional = rule.get("additionalProperties", True)',
        "            if additional is False and extras:",
        '                raise _wire_error(WIRE_UNKNOWN_FIELD, schema_name, f"{path}.{extras[0]}", "unknown field")',
        "            if isinstance(additional, Mapping):",
        "                for field in extras:",
        "                    _validate_wire_schema(",
        "                        additional, root, value[field], schema_name, f\"{path}.{field}\"",
        "                    )",
        "    if isinstance(value, list) and isinstance(rule.get(\"items\"), Mapping):",
        '        item_rule = rule["items"]',
        "        for index, item in enumerate(value):",
        '            _validate_wire_schema(item_rule, root, item, schema_name, f"{path}[{index}]")',
    ])
    for name, schema in schemas:
        const_name = f"_WIRE_SCHEMA_{name.upper()}"
        fn_name = f"validate_{_snake(name)}"
        body.append("")
        body.append(f"{const_name}: Dict[str, Any] = json.loads(r'''{_schema_json(schema)}''')")
        body.append("")
        body.append(f"def {fn_name}(value: Any) -> None:")
        body.append(f'    """Validate a value against wire/v1/{name}.schema.json."""')
        body.append(f'    _validate_wire_schema({const_name}, {const_name}, value, "{_camel(name)}", "$")')


# --- typescript --------------------------------------------------------

def ts_type(schema: dict, defs: dict, ctx: str) -> str:
    if "$ref" in schema:
        ref = schema["$ref"].split("/")[-1]
        return _camel(ref)
    if "oneOf" in schema or "anyOf" in schema:
        return "unknown"
    if "const" in schema:
        v = schema["const"]
        if isinstance(v, bool):
            return "true" if v else "false"
        if isinstance(v, int):
            return str(v)
        # Emit a JSON-style double-quoted string literal. Python's
        # `repr` would produce single quotes (`'foo'`) which TypeScript
        # accepts but diverges from what the other generators emit.
        return json.dumps(v)
    t = schema.get("type")
    if isinstance(t, list):
        return "unknown"
    if t == "string":
        if "enum" in schema:
            return " | ".join(json.dumps(e) for e in schema["enum"])
        return "string"
    if t == "integer" or t == "number":
        return "number"
    if t == "boolean":
        return "boolean"
    if t == "array":
        return f"{ts_type(schema.get('items', {}), defs, ctx)}[]"
    if t == "object":
        if "properties" in schema:
            return _camel(ctx)
        return "Record<string, unknown>"
    return "unknown"


def ts_interface(name: str, schema: dict, defs: dict, out: list[str]) -> None:
    props = schema.get("properties", {})
    required = set(schema.get("required", []))
    title = schema.get("title", name)
    description = schema.get("description", "")
    out.append("")
    out.append("/**")
    if title:
        out.append(f" * {title}.")
    for line in textwrap.wrap(description, 76):
        out.append(f" * {line}")
    out.append(" */")
    out.append(f"export interface {_camel(name)} {{")
    for pname, pschema in props.items():
        ty = ts_type(pschema, defs, f"{name}_{pname}")
        opt = "" if pname in required else "?"
        out.append(f"  {pname}{opt}: {ty};")
    out.append("}")


def emit_ts(schemas: list[tuple[str, dict]], contract: dict) -> str:
    body: list[str] = []
    body.append("// " + BANNER_LINES[0])
    for line in BANNER_LINES[1:]:
        body.append("// " + line)
    body.append("")
    body.append("/* eslint-disable */")
    body.append("")
    body.append(f"export const EXPECTED_WIRE_VERSION = {contract['wire_version']} as const;")
    body.append("")
    for name, schema in schemas:
        ts_interface(name, schema, schema.get("$defs", {}), body)
        nested: list[tuple[str, dict]] = []
        _collect_nested(name, schema, nested)
        for nname, nschema in nested:
            ts_interface(nname, nschema, schema.get("$defs", {}), body)
        for def_name, def_schema in schema.get("$defs", {}).items():
            ts_interface(def_name, def_schema, {}, body)
    _emit_ts_validation(body, _validation_targets(schemas, contract), contract)
    body.append("")
    return "\n".join(body) + "\n"


def _emit_ts_validation(
    body: list[str], schemas: list[tuple[str, dict]], contract: dict
) -> None:
    codes = contract["validation"]["error_codes"]
    body.extend([
        "",
        "/** Stable failure returned by generated wire validators. */",
        "export class WireDecodeError extends Error {",
        "  constructor(",
        "    readonly code: string,",
        "    readonly schema: string,",
        "    readonly path: string,",
        "    readonly reason: string,",
        "  ) {",
        "    super(`${code}: invalid ${schema} at ${path}: ${reason}`);",
        '    this.name = "WireDecodeError";',
        "  }",
        "}",
        "",
    ])
    for key, value in codes.items():
        body.append(f'export const WIRE_{key.upper()} = "{value}" as const;')
    body.extend([
        "",
        "type WireRule = Record<string, unknown>;",
        "",
        "function isRecord(value: unknown): value is Record<string, unknown> {",
        "  return typeof value === \"object\" && value !== null && !Array.isArray(value);",
        "}",
        "",
        "function wireError(code: string, schema: string, path: string, reason: string): WireDecodeError {",
        "  return new WireDecodeError(code, schema, path, reason);",
        "}",
        "",
        "function validateWireSchema(",
        "  rule: WireRule,",
        "  root: WireRule,",
        "  value: unknown,",
        "  schemaName: string,",
        "  path: string,",
        "): void {",
        '  const reference = rule["$ref"];',
        "  if (typeof reference === \"string\") {",
        '    const defs = root["$defs"];',
        "    const parts = reference.split(\"/\");",
        "    const target = isRecord(defs) ? defs[parts[parts.length - 1]] : undefined;",
        "    if (!isRecord(target)) {",
        "      throw wireError(WIRE_TYPE, schemaName, path, `unresolved schema reference ${reference}`);",
        "    }",
        "    validateWireSchema(target, root, value, schemaName, path);",
        "    return;",
        "  }",
        '  const branches = rule["oneOf"];',
        "  if (Array.isArray(branches)) {",
        "    let matches = 0;",
        "    for (const branch of branches) {",
        "      if (!isRecord(branch)) continue;",
        "      try {",
        "        validateWireSchema(branch, root, value, schemaName, path);",
        "        matches += 1;",
        "      } catch (error) {",
        "        if (!(error instanceof WireDecodeError)) throw error;",
        "      }",
        "    }",
        "    if (matches !== 1) {",
        '      throw wireError(WIRE_ONE_OF, schemaName, path, "expected exactly one allowed shape");',
        "    }",
        "    return;",
        "  }",
        '  const expected = rule["type"];',
        "  const valid =",
        '    expected === "object" ? isRecord(value) :',
        '    expected === "array" ? Array.isArray(value) :',
        '    expected === "string" ? typeof value === "string" :',
        '    expected === "integer" ? typeof value === "number" && Number.isInteger(value) :',
        '    expected === "number" ? typeof value === "number" && Number.isFinite(value) :',
        '    expected === "boolean" ? typeof value === "boolean" :',
        '    expected === "null" ? value === null : true;',
        "  if (typeof expected === \"string\" && !valid) {",
        "    throw wireError(WIRE_TYPE, schemaName, path, `expected ${expected}`);",
        "  }",
        '  if ("const" in rule && !Object.is(value, rule["const"])) {',
        '    throw wireError(WIRE_CONST, schemaName, path, "value does not match const");',
        "  }",
        '  const allowed = rule["enum"];',
        "  if (Array.isArray(allowed) && !allowed.some((entry) => Object.is(entry, value))) {",
        '    throw wireError(WIRE_ENUM, schemaName, path, "value is not in the allowed enum");',
        "  }",
        "  if (typeof value === \"number\") {",
        '    const minimum = rule["minimum"];',
        "    if (typeof minimum === \"number\" && value < minimum) {",
        "      throw wireError(WIRE_MINIMUM, schemaName, path, `must be >= ${minimum}`);",
        "    }",
        '    const maximum = rule["maximum"];',
        "    if (typeof maximum === \"number\" && value > maximum) {",
        "      throw wireError(WIRE_MAXIMUM, schemaName, path, `must be <= ${maximum}`);",
        "    }",
        "  }",
        "  if (isRecord(value)) {",
        '    const required = rule["required"];',
        "    if (Array.isArray(required)) {",
        "      for (const field of required) {",
        "        if (typeof field === \"string\" && !(field in value)) {",
        '          throw wireError(WIRE_REQUIRED, schemaName, `${path}.${field}`, "field is required");',
        "        }",
        "      }",
        "    }",
        '    const properties = rule["properties"];',
        "    if (isRecord(properties)) {",
        "      for (const field of Object.keys(properties).sort()) {",
        "        const fieldRule = properties[field];",
        "        if (field in value && isRecord(fieldRule)) {",
        "          validateWireSchema(fieldRule, root, value[field], schemaName, `${path}.${field}`);",
        "        }",
        "      }",
        "      const extras = Object.keys(value).filter((field) => !(field in properties)).sort();",
        '      const additional = rule["additionalProperties"];',
        "      if (additional === false && extras.length > 0) {",
        '        throw wireError(WIRE_UNKNOWN_FIELD, schemaName, `${path}.${extras[0]}`, "unknown field");',
        "      }",
        "      if (isRecord(additional)) {",
        "        for (const field of extras) {",
        "          validateWireSchema(additional, root, value[field], schemaName, `${path}.${field}`);",
        "        }",
        "      }",
        "    }",
        "  }",
        '  const itemRule = rule["items"];',
        "  if (Array.isArray(value) && isRecord(itemRule)) {",
        "    value.forEach((item, index) => {",
        "      validateWireSchema(itemRule, root, item, schemaName, `${path}[${index}]`);",
        "    });",
        "  }",
        "}",
    ])
    for name, schema in schemas:
        const_name = f"_WIRE_SCHEMA_{name.upper()}"
        fn_name = f"validate{_camel(name)}"
        type_name = _camel(name)
        body.append("")
        body.append(f"const {const_name}: WireRule = {_schema_json(schema)};")
        body.append("")
        body.append(
            f"export function {fn_name}(value: unknown): "
            f"asserts value is {type_name} & Record<string, unknown> {{"
        )
        body.append(f'  validateWireSchema({const_name}, {const_name}, value, "{type_name}", "$");')
        body.append("}")


# --- go ----------------------------------------------------------------

def go_type(schema: dict, defs: dict, ctx: str) -> str:
    if "x-go-type" in schema:
        return schema["x-go-type"]
    if "$ref" in schema:
        ref = schema["$ref"].split("/")[-1]
        return _camel(ref)
    if "oneOf" in schema or "anyOf" in schema:
        return "interface{}"
    if "const" in schema:
        return "int" if isinstance(schema["const"], int) else "string"
    t = schema.get("type")
    if isinstance(t, list):
        return "interface{}"
    if t == "string":
        return "string"
    if t == "integer":
        return "uint64" if schema.get("minimum", -1) >= 0 else "int64"
    if t == "number":
        return "float64"
    if t == "boolean":
        return "bool"
    if t == "array":
        return f"[]{go_type(schema.get('items', {}), defs, ctx)}"
    if t == "object":
        if "properties" in schema:
            return _camel(ctx)
        return "map[string]interface{}"
    return "interface{}"


def go_struct(name: str, schema: dict, defs: dict, out: list[str]) -> None:
    props = schema.get("properties", {})
    required = set(schema.get("required", []))
    title = schema.get("title", name)
    description = schema.get("description", "")
    if title:
        out.append(f"// {_camel(name)} — {title}.")
    for line in textwrap.wrap(description, 78):
        out.append(f"// {line}")
    out.append(f"type {_camel(name)} struct {{")
    for pname, pschema in props.items():
        ty = go_type(pschema, defs, f"{name}_{pname}")
        is_required = pname in required
        omit = "" if is_required else ",omitempty"
        # Go's `omitempty` is a no-op on non-pointer struct values: a
        # zero-valued nested struct still serialises as `{}`, which
        # diverges from what the Python/Rust/TS SDKs emit (they omit
        # the field entirely). For optional object-type fields we emit
        # a pointer (`*T`) so `omitempty` actually skips the key when
        # the field is `nil`.
        if not is_required and not _is_scalar_schema(pschema):
            ty = f"*{ty}"
        field = "".join(p.capitalize() for p in pname.replace("-", "_").split("_"))
        out.append(f'\t{field} {ty} `json:"{pname}{omit}"`')
    out.append("}")
    out.append("")


def emit_go(schemas: list[tuple[str, dict]], contract: dict) -> str:
    body: list[str] = []
    body.append("// " + BANNER_LINES[0])
    for line in BANNER_LINES[1:]:
        body.append("// " + line)
    body.append("")
    body.append("package clawossdk")
    body.append("")
    body.append("import (")
    body.append('\t"encoding/json"')
    body.append('\t"fmt"')
    body.append('\t"math"')
    body.append('\t"sort"')
    body.append('\t"strings"')
    body.append(")")
    body.append("")
    body.append(f"// ExpectedWireVersion is the wire-protocol version the kernel must")
    body.append(f"// advertise on every envelope. Mirrors generated.rs's")
    body.append(f"// EXPECTED_WIRE_VERSION.")
    body.append(f"const ExpectedWireVersion = {contract['wire_version']}")
    body.append("")
    body.append("// CheckWireVersion reports an error when the envelope's")
    body.append("// wire_version does not match what this SDK supports.")
    body.append("func CheckWireVersion(seen int) error {")
    body.append("\tif seen != ExpectedWireVersion {")
    body.append("\t\treturn fmt.Errorf(\"unsupported wire_version: got %d, expected %d\", seen, ExpectedWireVersion)")
    body.append("\t}")
    body.append("\treturn nil")
    body.append("}")
    body.append("")
    enum_validators: list[tuple[str, str, list]] = []
    for name, schema in schemas:
        go_struct(name, schema, schema.get("$defs", {}), body)
        nested: list[tuple[str, dict]] = []
        _collect_nested(name, schema, nested)
        for nname, nschema in nested:
            go_struct(nname, nschema, schema.get("$defs", {}), body)
        for def_name, def_schema in schema.get("$defs", {}).items():
            go_struct(def_name, def_schema, {}, body)
        _collect_enum_validators(name, schema, enum_validators)
        for nname, nschema in nested:
            _collect_enum_validators(nname, nschema, enum_validators)
    for parent, field_name, values in enum_validators:
        fn = f"Validate{_camel(parent)}{_camel(field_name)}"
        body.append(f"// {fn} reports an error if value is not in the {parent}.{field_name} enum.")
        body.append(f"func {fn}(value string) error {{")
        body.append("\tswitch value {")
        rendered = ", ".join(json.dumps(v) for v in values)
        body.append(f"\tcase {rendered}:")
        body.append("\t\treturn nil")
        body.append("\t}")
        body.append(f"\treturn fmt.Errorf(\"invalid {parent}.{field_name} value: %q\", value)")
        body.append("}")
        body.append("")
    _emit_go_validation(body, _validation_targets(schemas, contract), contract)
    return "\n".join(body)


def _emit_go_validation(
    body: list[str], schemas: list[tuple[str, dict]], contract: dict
) -> None:
    codes = contract["validation"]["error_codes"]
    body.extend([
        "// WireDecodeError is the stable failure returned by generated wire validators.",
        "type WireDecodeError struct {",
        "\tCode string",
        "\tSchema string",
        "\tPath string",
        "\tReason string",
        "}",
        "",
        "func (e *WireDecodeError) Error() string {",
        '\treturn fmt.Sprintf("%s: invalid %s at %s: %s", e.Code, e.Schema, e.Path, e.Reason)',
        "}",
        "",
        "const (",
    ])
    for key, value in codes.items():
        body.append(f'\tWire{_camel(key)} = "{value}"')
    body.extend([
        ")",
        "",
        "func wireError(code, schema, path, reason string) error {",
        "\treturn &WireDecodeError{Code: code, Schema: schema, Path: path, Reason: reason}",
        "}",
        "",
        "func wireRule(value any) (map[string]any, bool) {",
        "\trule, ok := value.(map[string]any)",
        "\treturn rule, ok",
        "}",
        "",
        "func wireNumber(value any) (float64, bool) {",
        "\tvar number float64",
        "\tswitch value := value.(type) {",
        "\tcase json.Number:",
        "\t\tparsed, err := value.Float64()",
        "\t\tif err != nil { return 0, false }",
        "\t\tnumber = parsed",
        "\tcase float64:",
        "\t\tnumber = value",
        "\tcase int:",
        "\t\tnumber = float64(value)",
        "\tcase int64:",
        "\t\tnumber = float64(value)",
        "\tcase uint64:",
        "\t\tnumber = float64(value)",
        "\tcase uint32:",
        "\t\tnumber = float64(value)",
        "\tdefault:",
        "\t\treturn 0, false",
        "\t}",
        "\treturn number, !math.IsInf(number, 0) && !math.IsNaN(number)",
        "}",
        "",
        "func validateWireSchema(rule, root map[string]any, value any, schemaName, path string) error {",
        '\tif reference, ok := rule["$ref"].(string); ok {',
        '\t\tdefs, _ := wireRule(root["$defs"])',
        '\t\tparts := strings.Split(reference, "/")',
        "\t\ttarget, found := wireRule(defs[parts[len(parts)-1]])",
        "\t\tif !found {",
        '\t\t\treturn wireError(WireType, schemaName, path, "unresolved schema reference "+reference)',
        "\t\t}",
        "\t\treturn validateWireSchema(target, root, value, schemaName, path)",
        "\t}",
        '\tif branches, ok := rule["oneOf"].([]any); ok {',
        "\t\tmatches := 0",
        "\t\tfor _, branchValue := range branches {",
        "\t\t\tbranch, valid := wireRule(branchValue)",
        "\t\t\tif valid && validateWireSchema(branch, root, value, schemaName, path) == nil {",
        "\t\t\t\tmatches++",
        "\t\t\t}",
        "\t\t}",
        "\t\tif matches != 1 {",
        '\t\t\treturn wireError(WireOneOf, schemaName, path, "expected exactly one allowed shape")',
        "\t\t}",
        "\t\treturn nil",
        "\t}",
        '\tif expected, ok := rule["type"].(string); ok {',
        "\t\tvalid := false",
        "\t\tswitch expected {",
        '\t\tcase "object":',
        "\t\t\t_, valid = value.(map[string]any)",
        '\t\tcase "array":',
        "\t\t\t_, valid = value.([]any)",
        '\t\tcase "string":',
        "\t\t\t_, valid = value.(string)",
        '\t\tcase "integer":',
        "\t\t\tnumber, numeric := wireNumber(value)",
        "\t\t\tvalid = numeric && math.Trunc(number) == number",
        '\t\tcase "number":',
        "\t\t\t_, valid = wireNumber(value)",
        '\t\tcase "boolean":',
        "\t\t\t_, valid = value.(bool)",
        '\t\tcase "null":',
        "\t\t\tvalid = value == nil",
        "\t\t}",
        "\t\tif !valid {",
        '\t\t\treturn wireError(WireType, schemaName, path, "expected "+expected)',
        "\t\t}",
        "\t}",
        '\tif expected, present := rule["const"]; present {',
        "\t\texpectedNumber, expectedNumeric := wireNumber(expected)",
        "\t\tactualNumber, actualNumeric := wireNumber(value)",
        "\t\tif (expectedNumeric && (!actualNumeric || expectedNumber != actualNumber)) || (!expectedNumeric && expected != value) {",
        '\t\t\treturn wireError(WireConst, schemaName, path, "value does not match const")',
        "\t\t}",
        "\t}",
        '\tif allowed, ok := rule["enum"].([]any); ok {',
        "\t\tmatched := false",
        "\t\tfor _, candidate := range allowed {",
        "\t\t\tif candidate == value { matched = true; break }",
        "\t\t}",
        "\t\tif !matched {",
        '\t\t\treturn wireError(WireEnum, schemaName, path, "value is not in the allowed enum")',
        "\t\t}",
        "\t}",
        "\tif number, numeric := wireNumber(value); numeric {",
        '\t\tif minimum, ok := wireNumber(rule["minimum"]); ok && number < minimum {',
        '\t\t\treturn wireError(WireMinimum, schemaName, path, fmt.Sprintf("must be >= %v", minimum))',
        "\t\t}",
        '\t\tif maximum, ok := wireNumber(rule["maximum"]); ok && number > maximum {',
        '\t\t\treturn wireError(WireMaximum, schemaName, path, fmt.Sprintf("must be <= %v", maximum))',
        "\t\t}",
        "\t}",
        "\tif object, ok := value.(map[string]any); ok {",
        '\t\tif required, ok := rule["required"].([]any); ok {',
        "\t\t\tfor _, fieldValue := range required {",
        "\t\t\t\tfield, _ := fieldValue.(string)",
        "\t\t\t\tif _, present := object[field]; !present {",
        '\t\t\t\t\treturn wireError(WireRequired, schemaName, path+"."+field, "field is required")',
        "\t\t\t\t}",
        "\t\t\t}",
        "\t\t}",
        '\t\tif properties, ok := wireRule(rule["properties"]); ok {',
        "\t\t\tnames := make([]string, 0, len(properties))",
        "\t\t\tfor name := range properties { names = append(names, name) }",
        "\t\t\tsort.Strings(names)",
        "\t\t\tfor _, name := range names {",
        "\t\t\t\tfieldValue, present := object[name]",
        "\t\t\t\tfieldRule, validRule := wireRule(properties[name])",
        "\t\t\t\tif present && validRule {",
        "\t\t\t\t\tif err := validateWireSchema(fieldRule, root, fieldValue, schemaName, path+\".\"+name); err != nil { return err }",
        "\t\t\t\t}",
        "\t\t\t}",
        "\t\t\textras := make([]string, 0)",
        "\t\t\tfor name := range object {",
        "\t\t\t\tif _, known := properties[name]; !known { extras = append(extras, name) }",
        "\t\t\t}",
        "\t\t\tsort.Strings(extras)",
        '\t\t\tif additional, ok := rule["additionalProperties"].(bool); ok && !additional && len(extras) > 0 {',
        '\t\t\t\treturn wireError(WireUnknownField, schemaName, path+"."+extras[0], "unknown field")',
        "\t\t\t}",
        '\t\t\tif additional, ok := wireRule(rule["additionalProperties"]); ok {',
        "\t\t\t\tfor _, name := range extras {",
        "\t\t\t\t\tif err := validateWireSchema(additional, root, object[name], schemaName, path+\".\"+name); err != nil { return err }",
        "\t\t\t\t}",
        "\t\t\t}",
        "\t\t}",
        "\t}",
        "\tif items, ok := value.([]any); ok {",
        '\t\tif itemRule, ok := wireRule(rule["items"]); ok {',
        "\t\t\tfor index, item := range items {",
        '\t\t\t\tif err := validateWireSchema(itemRule, root, item, schemaName, fmt.Sprintf("%s[%d]", path, index)); err != nil { return err }',
        "\t\t\t}",
        "\t\t}",
        "\t}",
        "\treturn nil",
        "}",
        "",
    ])
    for name, schema in schemas:
        const_name = f"wireSchema{_camel(name)}"
        fn_name = f"Validate{_camel(name)}"
        type_name = _camel(name)
        body.append(f"const {const_name} = {json.dumps(_schema_json(schema))}")
        body.append("")
        body.append(f"// {fn_name} validates a value against wire/v1/{name}.schema.json.")
        body.append(f"func {fn_name}(value any) error {{")
        body.append("\tvar schema map[string]any")
        body.append(f"\tdecoder := json.NewDecoder(strings.NewReader({const_name}))")
        body.append("\tdecoder.UseNumber()")
        body.append("\tif err := decoder.Decode(&schema); err != nil {")
        body.append('\t\tpanic("generated wire schema is invalid: " + err.Error())')
        body.append("\t}")
        body.append(f'\treturn validateWireSchema(schema, schema, value, "{type_name}", "$")')
        body.append("}")
        body.append("")


def emit_mcp_rust(contract: dict) -> str:
    codes = contract["json_rpc_error_codes"]
    body = [
        "// " + BANNER_LINES[0],
        "// Generated by claw-os-sdk/wire/codegen.py from wire/v1/contract.json.",
        "// Run `python3 wire/codegen.py` from the SDK root to regenerate.",
        "",
    ]
    for key, value in codes.items():
        body.append(f"pub const ERR_{key.upper()}: i64 = {value};")
    body.append("")
    return "\n".join(body)


# --- main --------------------------------------------------------------

def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when generated outputs differ without writing them",
    )
    args = parser.parse_args()
    schemas = load_schemas()
    if not schemas:
        print("no schemas found in", WIRE_DIR, file=sys.stderr)
        return 1
    contract = load_contract()
    envelope = dict(schemas)["envelope"]
    envelope_version = envelope["properties"]["wire_version"]["const"]
    if envelope_version != contract["wire_version"]:
        print(
            "contract wire_version does not match envelope schema const",
            file=sys.stderr,
        )
        return 1
    outputs = {
        RUST_OUT: emit_rust(schemas, contract),
        PY_OUT: emit_python(schemas, contract),
        TS_OUT: emit_ts(schemas, contract),
        GO_OUT: emit_go(schemas, contract),
        CORE_MCP_OUT: emit_mcp_rust(contract),
        CRATE_MCP_OUT: emit_mcp_rust(contract),
    }
    if args.check:
        stale = [
            path
            for path, content in outputs.items()
            if not path.exists() or path.read_text(encoding="utf-8") != content
        ]
        if stale:
            for path in stale:
                print(f"stale {path.relative_to(ROOT.parent)}", file=sys.stderr)
            return 1
        print("generated wire bindings are up to date")
        return 0
    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"wrote {path.relative_to(ROOT.parent)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
