#!/usr/bin/env python3
"""Codegen for claw-os-sdk wire/v1 schemas.

Reads every ``wire/v1/*.schema.json`` and emits typed bindings into each
language tree:

    rust/src/generated.rs            serde-friendly structs
    python/src/claw_os_sdk/generated.py    TypedDict definitions
    node/src/generated.ts            TypeScript interfaces
    go/generated.go                  Go structs

This is intentionally a small, hand-rolled emitter — no external generator
dependency. It handles the subset of JSON Schema used by wire/v1:

  - object with `properties` (+ `required`, `additionalProperties`)
  - primitive types: string, integer, number, boolean
  - arrays (with `items`)
  - `enum` ⇒ becomes a string with a doc-listed allow-list (kept loose to
    stay forward-compatible with kernel additions)
  - `const` (used for the wire_version field)
  - $defs / $ref for in-file definitions
  - oneOf (rendered as JsonValue / Any / unknown / any)

Run from the SDK root:

    python3 wire/codegen.py
"""

from __future__ import annotations

import json
import pathlib
import sys
import textwrap

ROOT = pathlib.Path(__file__).resolve().parent.parent
WIRE_DIR = ROOT / "wire" / "v1"
RUST_OUT = ROOT / "rust" / "src" / "generated.rs"
PY_OUT   = ROOT / "python" / "src" / "claw_os_sdk" / "generated.py"
TS_OUT   = ROOT / "node" / "src" / "generated.ts"
GO_OUT   = ROOT / "go" / "generated.go"

BANNER_LINES = [
    "DO NOT EDIT BY HAND.",
    "Generated by claw-os-sdk/wire/codegen.py from wire/v1/*.schema.json.",
    "Run `python3 wire/codegen.py` from the SDK root to regenerate.",
]


# --- helpers -----------------------------------------------------------

def _camel(name: str) -> str:
    parts = name.replace("-", "_").split("_")
    return "".join(p.capitalize() for p in parts if p)


def _snake(name: str) -> str:
    out = []
    for i, ch in enumerate(name):
        if ch.isupper() and i and not name[i - 1].isupper():
            out.append("_")
        out.append(ch.lower())
    return "".join(out).replace("-", "_")


def load_schemas() -> list[tuple[str, dict]]:
    schemas: list[tuple[str, dict]] = []
    for path in sorted(WIRE_DIR.glob("*.schema.json")):
        name = path.stem.replace(".schema", "")
        with path.open() as fh:
            schemas.append((name, json.load(fh)))
    return schemas


# --- rust --------------------------------------------------------------

def rust_type(schema: dict, defs: dict, ctx: str) -> str:
    if "$ref" in schema:
        ref = schema["$ref"].split("/")[-1]
        return _camel(ref)
    if "oneOf" in schema or "anyOf" in schema:
        return "serde_json::Value"
    if "const" in schema:
        return "u8" if isinstance(schema["const"], int) else "String"
    t = schema.get("type")
    if isinstance(t, list):
        return "serde_json::Value"
    if t == "string":
        return "String"
    if t == "integer":
        return "i64"
    if t == "number":
        return "f64"
    if t == "boolean":
        return "bool"
    if t == "array":
        inner = rust_type(schema.get("items", {}), defs, ctx)
        return f"Vec<{inner}>"
    if t == "object":
        if "properties" in schema:
            return _camel(ctx)
        return "serde_json::Value"
    return "serde_json::Value"


def _collect_nested(name: str, schema: dict, acc: list[tuple[str, dict]]) -> None:
    """Walk properties / items and collect anonymous nested objects.

    Each entry produced has a fully-qualified ctx name (e.g. ``ai_usage``)
    matching what ``*_type`` helpers compute, so emitters can generate
    matching standalone struct / interface definitions for them.
    """
    props = schema.get("properties", {})
    for pname, pschema in props.items():
        ctx = f"{name}_{pname}"
        if pschema.get("type") == "object" and "properties" in pschema:
            acc.append((ctx, pschema))
            _collect_nested(ctx, pschema, acc)
        elif pschema.get("type") == "array":
            items = pschema.get("items", {})
            if items.get("type") == "object" and "properties" in items:
                acc.append((ctx, items))
                _collect_nested(ctx, items, acc)


def rust_struct(name: str, schema: dict, defs: dict, out: list[str]) -> None:
    props = schema.get("properties", {})
    required = set(schema.get("required", []))
    title = schema.get("title", name)
    description = schema.get("description", "")
    doc = []
    if title:
        doc.append(f"/// {title}")
    for line in textwrap.wrap(description, 78):
        doc.append(f"/// {line}")
    if doc:
        out.extend(doc)
    out.append("#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]")
    out.append(f"pub struct {_camel(name)} {{")
    for pname, pschema in props.items():
        rust_ty = rust_type(pschema, defs, f"{name}_{pname}")
        rename = ""
        snake = _snake(pname)
        if snake != pname:
            rename = f'    #[serde(rename = "{pname}")]\n'
        if pname not in required:
            out.append(f'    #[serde(default, skip_serializing_if = "Option::is_none")]')
            out.append(f"{rename}    pub {snake}: Option<{rust_ty}>,")
        else:
            if rename:
                out.append(rename.rstrip())
            out.append(f"    pub {snake}: {rust_ty},")
    out.append("}")
    out.append("")


def emit_rust(schemas: list[tuple[str, dict]]) -> str:
    body: list[str] = []
    body.append("// " + BANNER_LINES[0])
    for line in BANNER_LINES[1:]:
        body.append("// " + line)
    body.append("")
    body.append("#![allow(clippy::all)]")
    body.append("#![allow(non_snake_case, non_camel_case_types)]")
    body.append("")
    body.append("use serde_json;")
    body.append("")
    for name, schema in schemas:
        rust_struct(name, schema, schema.get("$defs", {}), body)
        nested: list[tuple[str, dict]] = []
        _collect_nested(name, schema, nested)
        for nname, nschema in nested:
            rust_struct(nname, nschema, schema.get("$defs", {}), body)
        for def_name, def_schema in schema.get("$defs", {}).items():
            rust_struct(def_name, def_schema, {}, body)
    return "\n".join(body) + "\n"


# --- python ------------------------------------------------------------

def py_type(schema: dict, defs: dict, ctx: str) -> str:
    if "$ref" in schema:
        ref = schema["$ref"].split("/")[-1]
        return f'"{_camel(ref)}"'
    if "oneOf" in schema or "anyOf" in schema:
        return "Any"
    if "const" in schema:
        return "int" if isinstance(schema["const"], int) else "str"
    t = schema.get("type")
    if isinstance(t, list):
        return "Any"
    if t == "string":
        return "str"
    if t == "integer":
        return "int"
    if t == "number":
        return "float"
    if t == "boolean":
        return "bool"
    if t == "array":
        inner = py_type(schema.get("items", {}), defs, ctx)
        return f"List[{inner}]"
    if t == "object":
        if "properties" in schema:
            return f'"{_camel(ctx)}"'
        return "Dict[str, Any]"
    return "Any"


def py_typed_dict(name: str, schema: dict, defs: dict, out: list[str]) -> None:
    props = schema.get("properties", {})
    required = set(schema.get("required", []))
    title = schema.get("title", name)
    description = schema.get("description", "")
    out.append("")
    out.append(f"class {_camel(name)}(TypedDict, total=False):")
    out.append(f'    """{title}.')
    if description:
        out.append("")
        for line in textwrap.wrap(description, 76):
            out.append(f"    {line}")
    out.append('    """')
    if not props:
        out.append("    pass")
        return
    for pname, pschema in props.items():
        ty = py_type(pschema, defs, f"{name}_{pname}")
        marker = "  # required" if pname in required else ""
        out.append(f"    {pname}: {ty}{marker}")


def emit_python(schemas: list[tuple[str, dict]]) -> str:
    body: list[str] = []
    body.append('"""' + BANNER_LINES[0])
    for line in BANNER_LINES[1:]:
        body.append(line)
    body.append('"""')
    body.append("")
    body.append("from __future__ import annotations")
    body.append("")
    body.append("from typing import Any, Dict, List, TypedDict")
    body.append("")
    for name, schema in schemas:
        py_typed_dict(name, schema, schema.get("$defs", {}), body)
        nested: list[tuple[str, dict]] = []
        _collect_nested(name, schema, nested)
        for nname, nschema in nested:
            py_typed_dict(nname, nschema, schema.get("$defs", {}), body)
        for def_name, def_schema in schema.get("$defs", {}).items():
            py_typed_dict(def_name, def_schema, {}, body)
    body.append("")
    return "\n".join(body) + "\n"


# --- typescript --------------------------------------------------------

def ts_type(schema: dict, defs: dict, ctx: str) -> str:
    if "$ref" in schema:
        ref = schema["$ref"].split("/")[-1]
        return _camel(ref)
    if "oneOf" in schema or "anyOf" in schema:
        return "unknown"
    if "const" in schema:
        v = schema["const"]
        return repr(v) if isinstance(v, str) else str(v)
    t = schema.get("type")
    if isinstance(t, list):
        return "unknown"
    if t == "string":
        if "enum" in schema:
            return " | ".join(f'"{e}"' for e in schema["enum"])
        return "string"
    if t == "integer" or t == "number":
        return "number"
    if t == "boolean":
        return "boolean"
    if t == "array":
        return f"{ts_type(schema.get('items', {}), defs, ctx)}[]"
    if t == "object":
        if "properties" in schema:
            return _camel(ctx)
        return "Record<string, unknown>"
    return "unknown"


def ts_interface(name: str, schema: dict, defs: dict, out: list[str]) -> None:
    props = schema.get("properties", {})
    required = set(schema.get("required", []))
    title = schema.get("title", name)
    description = schema.get("description", "")
    out.append("")
    out.append("/**")
    if title:
        out.append(f" * {title}.")
    for line in textwrap.wrap(description, 76):
        out.append(f" * {line}")
    out.append(" */")
    out.append(f"export interface {_camel(name)} {{")
    for pname, pschema in props.items():
        ty = ts_type(pschema, defs, f"{name}_{pname}")
        opt = "" if pname in required else "?"
        out.append(f"  {pname}{opt}: {ty};")
    out.append("}")


def emit_ts(schemas: list[tuple[str, dict]]) -> str:
    body: list[str] = []
    body.append("// " + BANNER_LINES[0])
    for line in BANNER_LINES[1:]:
        body.append("// " + line)
    body.append("")
    body.append("/* eslint-disable */")
    body.append("")
    for name, schema in schemas:
        ts_interface(name, schema, schema.get("$defs", {}), body)
        nested: list[tuple[str, dict]] = []
        _collect_nested(name, schema, nested)
        for nname, nschema in nested:
            ts_interface(nname, nschema, schema.get("$defs", {}), body)
        for def_name, def_schema in schema.get("$defs", {}).items():
            ts_interface(def_name, def_schema, {}, body)
    body.append("")
    return "\n".join(body) + "\n"


# --- go ----------------------------------------------------------------

def go_type(schema: dict, defs: dict, ctx: str) -> str:
    if "$ref" in schema:
        ref = schema["$ref"].split("/")[-1]
        return _camel(ref)
    if "oneOf" in schema or "anyOf" in schema:
        return "interface{}"
    if "const" in schema:
        return "int" if isinstance(schema["const"], int) else "string"
    t = schema.get("type")
    if isinstance(t, list):
        return "interface{}"
    if t == "string":
        return "string"
    if t == "integer":
        return "int64"
    if t == "number":
        return "float64"
    if t == "boolean":
        return "bool"
    if t == "array":
        return f"[]{go_type(schema.get('items', {}), defs, ctx)}"
    if t == "object":
        if "properties" in schema:
            return _camel(ctx)
        return "map[string]interface{}"
    return "interface{}"


def go_struct(name: str, schema: dict, defs: dict, out: list[str]) -> None:
    props = schema.get("properties", {})
    required = set(schema.get("required", []))
    title = schema.get("title", name)
    description = schema.get("description", "")
    if title:
        out.append(f"// {_camel(name)} — {title}.")
    for line in textwrap.wrap(description, 78):
        out.append(f"// {line}")
    out.append(f"type {_camel(name)} struct {{")
    for pname, pschema in props.items():
        ty = go_type(pschema, defs, f"{name}_{pname}")
        omit = "" if pname in required else ",omitempty"
        field = "".join(p.capitalize() for p in pname.replace("-", "_").split("_"))
        out.append(f'\t{field} {ty} `json:"{pname}{omit}"`')
    out.append("}")
    out.append("")


def emit_go(schemas: list[tuple[str, dict]]) -> str:
    body: list[str] = []
    body.append("// " + BANNER_LINES[0])
    for line in BANNER_LINES[1:]:
        body.append("// " + line)
    body.append("")
    body.append("package clawossdk")
    body.append("")
    for name, schema in schemas:
        go_struct(name, schema, schema.get("$defs", {}), body)
        nested: list[tuple[str, dict]] = []
        _collect_nested(name, schema, nested)
        for nname, nschema in nested:
            go_struct(nname, nschema, schema.get("$defs", {}), body)
        for def_name, def_schema in schema.get("$defs", {}).items():
            go_struct(def_name, def_schema, {}, body)
    return "\n".join(body)


# --- main --------------------------------------------------------------

def main() -> int:
    schemas = load_schemas()
    if not schemas:
        print("no schemas found in", WIRE_DIR, file=sys.stderr)
        return 1
    RUST_OUT.parent.mkdir(parents=True, exist_ok=True)
    PY_OUT.parent.mkdir(parents=True, exist_ok=True)
    TS_OUT.parent.mkdir(parents=True, exist_ok=True)
    GO_OUT.parent.mkdir(parents=True, exist_ok=True)
    RUST_OUT.write_text(emit_rust(schemas))
    PY_OUT.write_text(emit_python(schemas))
    TS_OUT.write_text(emit_ts(schemas))
    GO_OUT.write_text(emit_go(schemas))
    print(f"wrote {RUST_OUT.relative_to(ROOT)}")
    print(f"wrote {PY_OUT.relative_to(ROOT)}")
    print(f"wrote {TS_OUT.relative_to(ROOT)}")
    print(f"wrote {GO_OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
