// DO NOT EDIT BY HAND.
// Generated by claw-os-sdk/wire/codegen.py from wire/v1/contract.json.
// Run `python3 wire/codegen.py` from the SDK root to regenerate.

pub const ERR_INTERNAL: i64 = -32603;
pub const ERR_INVALID_PARAMS: i64 = -32602;
pub const ERR_INVALID_REQUEST: i64 = -32600;
pub const ERR_METHOD_NOT_FOUND: i64 = -32601;
pub const ERR_PARSE: i64 = -32700;
