// DO NOT EDIT BY HAND.
// Generated by claw-os-sdk/wire/codegen.py from wire/v1/*.schema.json.
// Run `python3 wire/codegen.py` from the SDK root to regenerate.

package clawossdk

// Ai — AI request / reply.
// Shape of the data payload returned by `cos ai chat|embed|image-generate`. Apps
// call this via SDK helpers (claw_os_sdk.ai.chat / ai.embed /
// ai.image_generate). The kernel emits the same fields whether the call was
// synchronous or streamed (terminating reply).
type Ai struct {
	Verb string `json:"verb"`
	Text string `json:"text,omitempty"`
	Model string `json:"model,omitempty"`
	Provider string `json:"provider,omitempty"`
	Embedding []float64 `json:"embedding,omitempty"`
	Embeddings [][]float64 `json:"embeddings,omitempty"`
	OutputPath string `json:"output_path,omitempty"`
	Usage AiUsage `json:"usage,omitempty"`
	Budget AiBudget `json:"budget,omitempty"`
	Review AiReview `json:"review,omitempty"`
	ToolCalls []AiToolCalls `json:"tool_calls,omitempty"`
	Raw interface{} `json:"raw,omitempty"`
}

// AiUsage — ai_usage.
// Token / unit accounting for this single call.
type AiUsage struct {
	InputTokens int64 `json:"input_tokens,omitempty"`
	OutputTokens int64 `json:"output_tokens,omitempty"`
	Units float64 `json:"units,omitempty"`
}

// AiBudget — ai_budget.
// Snapshot of the app's budget *after* this call.
type AiBudget struct {
	Period string `json:"period,omitempty"`
	UnitsUsed float64 `json:"units_used,omitempty"`
	UnitsCap float64 `json:"units_cap,omitempty"`
}

// AiReview — ai_review.
// Safety / review metadata.
type AiReview struct {
	Safety string `json:"safety,omitempty"`
	PromptRedacted bool `json:"prompt_redacted,omitempty"`
	ResponseBlocked bool `json:"response_blocked,omitempty"`
}

// AiToolCalls — ai_tool_calls.
type AiToolCalls struct {
	Name string `json:"name"`
	Args map[string]interface{} `json:"args,omitempty"`
	Result interface{} `json:"result,omitempty"`
}

// App — App-verb invocation reply.
// Reply shape for `cos app <id> <verb> [args]`. The payload is the verb's own
// JSON output — what schema you get depends on which verb you called. The kernel
// guarantees only that the body is valid JSON (or stderr-routed when stdout
// would be ambiguous).
type App struct {
	Verb string `json:"verb,omitempty"`
	App string `json:"app,omitempty"`
}

// Envelope — Envelope.
// Common wrapper around every wire v1 reply. Forward-compatible target shape —
// the current kernel still emits flat per-command shapes that SDKs adapt to this
// envelope.
type Envelope struct {
	Ok bool `json:"ok"`
	WireVersion int `json:"wire_version"`
	AuditId string `json:"audit_id,omitempty"`
	Data map[string]interface{} `json:"data,omitempty"`
	Error string `json:"error,omitempty"`
	Code string `json:"code,omitempty"`
	Detail map[string]interface{} `json:"detail,omitempty"`
}

// Manifest — App manifest (app.json).
// The manifest every app under COS_APPS_DIR must provide. The kernel validates
// and uses this to derive declared verbs, runtime, and capability requirements.
type Manifest struct {
	Id string `json:"id"`
	Name string `json:"name"`
	Version string `json:"version,omitempty"`
	Runtime string `json:"runtime"`
	Entry string `json:"entry,omitempty"`
	Verbs []ManifestVerbs `json:"verbs"`
}

// ManifestVerbs — manifest_verbs.
type ManifestVerbs struct {
	Name string `json:"name"`
	Summary string `json:"summary,omitempty"`
	Args []Arg `json:"args,omitempty"`
	Needs []Caprequest `json:"needs,omitempty"`
	SideEffects bool `json:"side_effects,omitempty"`
}

// Arg — arg.
type Arg struct {
	Name string `json:"name"`
	Kind string `json:"kind"`
	Required bool `json:"required,omitempty"`
}

// Caprequest — capRequest.
type Caprequest struct {
	Verb string `json:"verb"`
	Scope interface{} `json:"scope,omitempty"`
}

// Perms — Permissions request / reply.
// Shape of the success-path data field returned by `cos perms check`. Apps call
// this via SDK helpers (e.g. claw_os_sdk.policy.check).
type Perms struct {
	Decision string `json:"decision"`
	Verb string `json:"verb"`
	Scope interface{} `json:"scope,omitempty"`
	Reason string `json:"reason,omitempty"`
	Hint string `json:"hint,omitempty"`
	Granted bool `json:"granted,omitempty"`
}

// Tool — Catalog tool invocation reply.
// Shape returned by `cos ai tool <name> --app <id> --args '<json>'`. Catalog
// tools are reusable functions exposed in the AI tool catalog. They differ from
// app verbs in that the AI plans them automatically.
type Tool struct {
	Tool string `json:"tool"`
	Result interface{} `json:"result,omitempty"`
	AuditId string `json:"audit_id,omitempty"`
}
