// DO NOT EDIT BY HAND.
// Generated by claw-os-sdk/wire/codegen.py from wire/v1/*.schema.json.
// Run `python3 wire/codegen.py` from the SDK root to regenerate.

package clawossdk

import "fmt"

// ExpectedWireVersion is the wire-protocol version the kernel must
// advertise on every envelope. Mirrors generated.rs's
// EXPECTED_WIRE_VERSION.
const ExpectedWireVersion = 1

// CheckWireVersion reports an error when the envelope's
// wire_version does not match what this SDK supports.
func CheckWireVersion(seen int) error {
	if seen != ExpectedWireVersion {
		return fmt.Errorf("unsupported wire_version: got %d, expected %d", seen, ExpectedWireVersion)
	}
	return nil
}

// Ai — AI request / reply.
// Stable text-chat reply returned by `cos ai chat`.
type Ai struct {
	Text string `json:"text"`
	Model string `json:"model"`
	Provider string `json:"provider"`
	Verb string `json:"verb"`
	Usage AiUsage `json:"usage"`
	Budget AiBudget `json:"budget"`
	Review AiReview `json:"review"`
	ToolCalls []AiToolCall `json:"tool_calls,omitempty"`
}

// AiUsage — ai_usage.
// Token and unit accounting for this call.
type AiUsage struct {
	InputTokens uint32 `json:"input_tokens"`
	OutputTokens uint32 `json:"output_tokens"`
	Units uint64 `json:"units"`
}

// AiBudget — ai_budget.
// App budget snapshot after the call.
type AiBudget struct {
	Period string `json:"period"`
	UnitsUsed uint64 `json:"units_used"`
	UnitsCap uint64 `json:"units_cap"`
}

// AiReview — ai_review.
// Safety policy actually applied by the kernel.
type AiReview struct {
	Safety string `json:"safety"`
	PromptRedacted bool `json:"prompt_redacted"`
}

// AiToolCall — AiToolCall.
type AiToolCall struct {
	Id string `json:"id"`
	Name string `json:"name"`
	Input interface{} `json:"input"`
}

// App — App-verb invocation reply.
// Reply shape for `cos app <id> <verb> [args]`. The payload is the verb's own
// JSON output — what schema you get depends on which verb you called. The kernel
// guarantees only that the body is valid JSON (or stderr-routed when stdout
// would be ambiguous).
type App struct {
	Verb string `json:"verb,omitempty"`
	App string `json:"app,omitempty"`
}

// Envelope — Envelope.
// Common wrapper around every wire v1 reply. Forward-compatible target shape —
// the current kernel still emits flat per-command shapes that SDKs adapt to this
// envelope.
type Envelope struct {
	Ok bool `json:"ok"`
	WireVersion int `json:"wire_version"`
	AuditId string `json:"audit_id,omitempty"`
	Data map[string]interface{} `json:"data,omitempty"`
	Error string `json:"error,omitempty"`
	Code string `json:"code,omitempty"`
	Detail map[string]interface{} `json:"detail,omitempty"`
}

// Manifest — App manifest (app.json).
// The manifest every app under COS_APPS_DIR must provide. The kernel parses and
// validates this (core/src/caps/manifest.rs) to derive the app's operations,
// optional MCP session tools, optional desktop GUI surface, capability needs,
// and AI policy.
type Manifest struct {
	Id string `json:"id"`
	Version string `json:"version"`
	Name Localizedtext `json:"name"`
	Summary *Localizedtext `json:"summary,omitempty"`
	Icon string `json:"icon,omitempty"`
	Runtime string `json:"runtime,omitempty"`
	Entry string `json:"entry,omitempty"`
	Operations map[string]interface{} `json:"operations,omitempty"`
	Ai *Aipolicy `json:"ai,omitempty"`
	Session *Session `json:"session,omitempty"`
	Desktop *Desktop `json:"desktop,omitempty"`
	Dependencies map[string]interface{} `json:"dependencies,omitempty"`
}

// Localizedtext — localizedText.
// Localized string map. The `en` key is required; other locales (zh-CN, ...) are
// optional fallbacks.
type Localizedtext struct {
	En string `json:"en"`
}

// Operation — operation.
// A one-shot operation: its inputs and the capabilities it needs.
type Operation struct {
	Label Localizedtext `json:"label"`
	Summary *Localizedtext `json:"summary,omitempty"`
	Args []Arg `json:"args,omitempty"`
	Needs []Need `json:"needs,omitempty"`
}

// Arg — arg.
type Arg struct {
	Name string `json:"name"`
	Kind string `json:"kind"`
	Required bool `json:"required,omitempty"`
	Default *interface{} `json:"default,omitempty"`
	Label *Localizedtext `json:"label,omitempty"`
}

// Need — need.
// A single capability request: verb + scope binding + human reason.
type Need struct {
	Verb string `json:"verb"`
	Scope Scopebinding `json:"scope"`
	Why Localizedtext `json:"why"`
}

// Scopebinding — scopeBinding.
// How an operation's scope is determined at invocation time. kind=from-arg reads
// a named arg at call time; kind=fixed hard-codes a scope; kind=wild is an
// explicit wildcard (no implicit '*').
type Scopebinding struct {
	Kind string `json:"kind"`
	Arg string `json:"arg,omitempty"`
	Scope *Scope `json:"scope,omitempty"`
}

// Scope — scope.
// A concrete capability scope. value is a glob for path/host/name, the self-
// reference string for self-ref, and absent for wild.
type Scope struct {
	Kind string `json:"kind"`
	Value string `json:"value,omitempty"`
}

// Aipolicy — aiPolicy.
// Budget + safety envelope under which the app may exercise ai.* verbs. Apps
// never pick the model; the OS owns the provider.
type Aipolicy struct {
	Budget Aibudget `json:"budget"`
	Safety string `json:"safety,omitempty"`
	Origins []string `json:"origins,omitempty"`
	Tools []string `json:"tools,omitempty"`
}

// Aibudget — aiBudget.
type Aibudget struct {
	MonthlyUnits uint64 `json:"monthly_units,omitempty"`
}

// Session — session.
// Long-lived MCP server the app launches for stateful, agent-driven tool calls.
type Session struct {
	Entry string `json:"entry,omitempty"`
	Transport string `json:"transport,omitempty"`
	Tools []Sessiontool `json:"tools,omitempty"`
}

// Sessiontool — sessionTool.
// One MCP-callable tool. Mirrors operation: args + needs drive the model's view
// and the kernel's enforcement.
type Sessiontool struct {
	Name string `json:"name"`
	Summary Localizedtext `json:"summary"`
	Args []Arg `json:"args,omitempty"`
	Needs []Need `json:"needs,omitempty"`
}

// Desktop — desktop.
// Desktop GUI surface. Drives generation of
// /usr/share/applications/com.clawos.<Id>.desktop at install time.
type Desktop struct {
	Exec string `json:"exec,omitempty"`
	Name *Localizedtext `json:"name,omitempty"`
	Icon string `json:"icon,omitempty"`
	Categories []string `json:"categories,omitempty"`
	MimeTypes []string `json:"mime_types,omitempty"`
	SingleInstance bool `json:"single_instance,omitempty"`
	PanelApplet bool `json:"panel_applet,omitempty"`
}

// Perms — Permissions request / reply.
// Shape of the success-path data field returned by policy checks. Apps call this
// via SDK helpers (e.g. cos_runtime.policy.check).
type Perms struct {
	Decision string `json:"decision"`
	Verb string `json:"verb"`
	Scope interface{} `json:"scope,omitempty"`
	Reason string `json:"reason,omitempty"`
	Hint string `json:"hint,omitempty"`
	Granted bool `json:"granted,omitempty"`
}

// Tool — Catalog tool invocation reply.
// Shape returned by `cos ai tool <name> --app <id> --args '<json>'`.
type Tool struct {
	Tool string `json:"tool"`
	AppId string `json:"app_id"`
	Status string `json:"status"`
	Result interface{} `json:"result"`
}

// ValidateAiVerb reports an error if value is not in the ai.verb enum.
func ValidateAiVerb(value string) error {
	switch value {
	case "ai.chat", "ai.chat.untrusted":
		return nil
	}
	return fmt.Errorf("invalid ai.verb value: %q", value)
}

// ValidateAiReviewSafety reports an error if value is not in the ai_review.safety enum.
func ValidateAiReviewSafety(value string) error {
	switch value {
	case "strict", "standard", "minimal":
		return nil
	}
	return fmt.Errorf("invalid ai_review.safety value: %q", value)
}

// ValidateManifestRuntime reports an error if value is not in the manifest.runtime enum.
func ValidateManifestRuntime(value string) error {
	switch value {
	case "python", "node", "shell", "binary":
		return nil
	}
	return fmt.Errorf("invalid manifest.runtime value: %q", value)
}

// ValidatePermsDecision reports an error if value is not in the perms.decision enum.
func ValidatePermsDecision(value string) error {
	switch value {
	case "allow", "deny", "prompt":
		return nil
	}
	return fmt.Errorf("invalid perms.decision value: %q", value)
}

// ValidateToolStatus reports an error if value is not in the tool.status enum.
func ValidateToolStatus(value string) error {
	switch value {
	case "ok":
		return nil
	}
	return fmt.Errorf("invalid tool.status value: %q", value)
}
